In [50]:
from datasets import load_dataset

df = load_dataset("lukebarousse/data_jobs")["train"].to_pandas()

In [46]:
df[df["salary_hour_avg"].notna()]           # Before droping Null values

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
43,Senior Data Engineer,Sr SQL Database Engineer with Data Warehouse /...,NaN,via LinkedIn,Contractor,False,"Texas, United States",2023-09-13 13:06:55,True,False,United States,hour,NaN,97.500000,Phaxis,"['sql', 'sql server']","{'databases': ['sql server'], 'programming': [..."
51,Senior Data Engineer,Senior Data Engineer,Anywhere,via LinkedIn,Contractor,True,"Illinois, United States",2023-06-21 13:09:39,False,False,United States,hour,NaN,72.500000,Aditi Consulting,"['python', 'java', 'aws', 'databricks', 'spark']","{'cloud': ['aws', 'databricks'], 'libraries': ..."
253,Data Engineer,Data Engineer,Anywhere,via Upwork,Contractor and Temp work,True,Georgia,2023-11-26 13:54:45,True,False,United States,hour,NaN,88.000000,Upwork,"['sql', 'python', 'java', 'mysql', 'postgresql...","{'cloud': ['aws', 'gcp'], 'databases': ['mysql..."
294,Data Analyst,Business/Data Analyst,"Hartford, CT",via Dice,Contractor,False,"New York, United States",2023-07-03 13:00:08,False,False,United States,hour,NaN,52.500000,"Vector Consulting, Inc",NaN,NaN
340,Data Analyst,23-00059 BI Data Analysts + Media experience -...,California,via LinkedIn,Contractor,False,"California, United States",2023-02-28 13:01:46,True,False,United States,hour,NaN,67.500000,"iSpace, Inc.","['go', 'sql', 'aws', 'snowflake', 'tableau', '...","{'analyst_tools': ['tableau', 'looker', 'word'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
784068,Data Engineer,"Manager, Data Engineering","New York, NY",via Snagajob,Full-time,False,Sudan,2023-08-12 06:37:26,False,True,Sudan,hour,NaN,54.420002,Vibrant Emotional Health,"['sql', 'python', 'r', 'snowflake', 'aws']","{'cloud': ['snowflake', 'aws'], 'programming':..."
784267,Senior Data Engineer,Senior Lead Data Engineer - Now Hiring,"Fredericksburg, VA",via Snagajob,Full-time and Part-time,False,"California, United States",2023-11-13 06:03:59,False,True,United States,hour,NaN,61.159996,Capital One,"['java', 'scala', 'python', 'nosql', 'sql', 'm...","{'cloud': ['redshift', 'snowflake', 'aws', 'az..."
785111,Senior Data Engineer,"Health and Civil Data Engineer, Senior - Now H...","Bethesda, MD",via Snagajob,Full-time and Part-time,False,Georgia,2023-10-08 06:50:59,False,True,United States,hour,NaN,61.159996,Booz Allen Hamilton,"['python', 'sql', 'scala', 'java', 'shell', 'n...","{'cloud': ['aws', 'azure', 'databricks', 'reds..."
785476,Data Scientist,"Data Scientist, Lead","Washington, DC",via Snagajob,Full-time and Part-time,False,Georgia,2023-11-01 06:58:10,False,True,United States,hour,NaN,47.620003,Booz Allen Hamilton,"['databricks', 'azure', 'aws']","{'cloud': ['databricks', 'azure', 'aws']}"
785492,Data Scientist,Data Scientist,"Arlington, VA",via Snagajob,Full-time and Part-time,False,Georgia,2023-11-01 06:58:02,False,True,United States,hour,NaN,47.620003,Booz Allen Hamilton,"['python', 'r', 'pyspark']","{'libraries': ['pyspark'], 'programming': ['py..."

In [48]:
# after droping Null values of salary_year_avg column

df[df["salary_hour_avg"].notna()]

Empty DataFrame
Columns: [job_title_short, job_title, job_location, job_via, job_schedule_type, job_work_from_home, search_location, job_posted_date, job_no_degree_mention, job_health_insurance, job_country, salary_rate, salary_year_avg, salary_hour_avg, company_name, job_skills, job_type_skills]
Index: []

In [2]:
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [20]:
import pandas as pd

In [47]:
df.dropna(subset="salary_year_avg", inplace=True)


df["job_posted_date"] = pd.to_datetime(df["job_posted_date"])

In [7]:
df.info()

<class 'pandas.DataFrame'>
Index: 22003 entries, 28 to 785692
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   job_title_short        22003 non-null  str
 1   job_title              22003 non-null  str
 2   job_location           21723 non-null  str
 3   job_via                22003 non-null  str
 4   job_schedule_type      21987 non-null  str
 5   job_work_from_home     22003 non-null  bool
 6   search_location        22003 non-null  str
 7   job_posted_date        22003 non-null  datetime64[us]
 8   job_no_degree_mention  22003 non-null  bool
 9   job_health_insurance   22003 non-null  bool
 10  job_country            22003 non-null  str
 11  salary_rate            22003 non-null  str
 12  salary_year_avg        22003 non-null  float64
 13  salary_hour_avg        0 non-null      float64
 14  company_name           22003 non-null  str
 15  job_skills             20170 non-null  str
 16  job_type_skills        20170 non-null  str
dtypes: bool(3), datetime64[us](1), float64(2), str(11)
memory usage: 8.2 MB

In [4]:
df["job_title_short"].value_counts()

# or

df.groupby("job_title_short")["salary_year_avg"].count()

job_title_short
Business Analyst              610
Cloud Engineer                 65
Data Analyst                 5451
Data Engineer                4500
Data Scientist               5922
Machine Learning Engineer     576
Senior Data Analyst          1131
Senior Data Engineer         1591
Senior Data Scientist        1690
Software Engineer             467
Name: salary_year_avg, dtype: int64

In [6]:
df.groupby("job_title_short")

In [7]:
df.groupby("job_title_short")["salary_year_avg"]

In [9]:
df.groupby("job_title_short")["salary_year_avg"].sum()

job_title_short
Business Analyst             5.556039e+07
Cloud Engineer               7.232450e+06
Data Analyst                 5.115322e+08
Data Engineer                5.855652e+08
Data Scientist               8.053259e+08
Machine Learning Engineer    7.302201e+07
Senior Data Analyst          1.288338e+08
Senior Data Engineer         2.320324e+08
Senior Data Scientist        2.606086e+08
Software Engineer            5.295489e+07
Name: salary_year_avg, dtype: float64

In [11]:
df.groupby("job_title_short")["salary_year_avg"].mean()

job_title_short
Business Analyst              91082.612833
Cloud Engineer               111268.453846
Data Analyst                  93841.907854
Data Engineer                130125.604250
Data Scientist               135988.837171
Machine Learning Engineer    126774.315972
Senior Data Analyst          113911.363665
Senior Data Engineer         145840.611624
Senior Data Scientist        154206.292996
Software Engineer            113393.760054
Name: salary_year_avg, dtype: float64

In [8]:
df.groupby("job_title_short")["salary_year_avg"].min()

job_title_short
Business Analyst             16500.0
Cloud Engineer               42000.0
Data Analyst                 25000.0
Data Engineer                15000.0
Data Scientist               27000.0
Machine Learning Engineer    30000.0
Senior Data Analyst          30000.0
Senior Data Engineer         35000.0
Senior Data Scientist        45000.0
Software Engineer            28000.0
Name: salary_year_avg, dtype: float64

In [12]:
df[(df["job_title_short"] == "Data Engineer") & (df["salary_year_avg"] == 15000)]       # Checking and extracting

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
665729,Data Engineer,Data Engineer - Hadoop,Brazil,via LinkedIn,Full-time,False,Brazil,2023-12-09 10:05:30,True,False,Brazil,year,15000.0,NaN,Net2Source Inc.,"['java', 'python', 'oracle', 'aws', 'hadoop', ...","{'cloud': ['oracle', 'aws'], 'libraries': ['ha..."

In [15]:
df.groupby(["job_title_short", "job_country"])["salary_year_avg"].sum()

job_title_short    job_country
Business Analyst   Afghanistan         0.0
                   Albania             0.0
                   Algeria             0.0
                   Angola              0.0
                   Argentina      142200.0
                                    ...
Software Engineer  Venezuela           0.0
                   Vietnam        107200.0
                   Yemen               0.0
                   Zambia              0.0
                   Zimbabwe            0.0
Name: salary_year_avg, Length: 1387, dtype: float64

In [ ]:
df[df["job_country"] == "Albania"]          # before droping the nan values

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
3095,Data Engineer,Oracle Data Engineer,"Tirana, Albania",via LinkedIn Albania,Full-time,False,Albania,2023-01-24 14:02:15,False,False,Albania,NaN,NaN,NaN,3i Solutions Albania,"['sql', 'oracle', 'databricks', 'spark', 'kafka']","{'cloud': ['oracle', 'databricks'], 'libraries..."
5194,Senior Data Scientist,"Senior Data Scientist (f/m/x), Albania","Tirana, Albania",via LinkedIn Albania,Full-time,False,Albania,2023-06-02 14:16:51,False,False,Albania,NaN,NaN,NaN,AUTO1 Group,"['sql', 'python']","{'programming': ['sql', 'python']}"
5284,Data Engineer,Data Engineer,"Kashar, Albania",via Vodafone Careers,Full-time,False,Albania,2023-07-11 14:12:23,False,False,Albania,NaN,NaN,NaN,Vodafone,"['sql', 'oracle', 'gcp', 'bigquery']","{'cloud': ['oracle', 'gcp', 'bigquery'], 'prog..."
9047,Business Analyst,Business Intelligence Analyst,"Tirana, Albania",via LinkedIn Albania,Full-time,False,Albania,2023-08-09 14:21:41,True,False,Albania,NaN,NaN,NaN,BULLS MEDIA ALBANIA,"['sql', 'python', 'power bi', 'dax', 'sheets']","{'analyst_tools': ['power bi', 'dax', 'sheets'..."
9897,Data Engineer,Data Engineer,"Vlorë, Albania",via LinkedIn Albania,Full-time,False,Albania,2023-08-04 14:05:13,True,False,Albania,NaN,NaN,NaN,Mindpal,"['scala', 'python', 'sql', 'hadoop', 'spark']","{'libraries': ['hadoop', 'spark'], 'programmin..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
679738,Senior Data Scientist,"Senior Data Scientist (f/m/x), Albania","Tirana, Albania",via AI Careers,Full-time,False,Albania,2023-05-26 10:42:05,False,False,Albania,NaN,NaN,NaN,AUTO1 Group,NaN,NaN
686360,Software Engineer,Back-End/Laravel Software Engineer,"Tirana, Albania",via LinkedIn Albania,Full-time,False,Albania,2023-01-23 11:29:05,False,False,Albania,NaN,NaN,NaN,Marine Data Cloud,"['php', 'mongodb', 'mongodb', 'mysql', 'fireba...","{'async': ['jira', 'confluence'], 'cloud': ['f..."
721510,Data Engineer,Sn. Data Engineer,"Kashar, Albania",via Jobs At Vodafone,Full-time,False,Albania,2023-03-11 22:12:08,True,False,Albania,NaN,NaN,NaN,Vodafone,"['python', 'java', 'shell', 'oracle', 'unix']","{'cloud': ['oracle'], 'os': ['unix'], 'program..."
724547,Software Engineer,Developer Advocate,Anywhere,via AngelList,Full-time,True,Albania,2023-01-23 22:29:05,True,False,Albania,NaN,NaN,NaN,Y42,"['snowflake', 'bigquery', 'redshift', 'airflow...","{'analyst_tools': ['word'], 'cloud': ['snowfla..."
736852,Data Engineer,Data Network Operations Engineer,"Kashar, Albania",via Jobs At Vodafone,Full-time,False,Albania,2023-03-04 21:58:22,False,False,Albania,NaN,NaN,NaN,Vodafone,NaN,NaN

In [27]:
df[(df["job_country"] == "Albania") & (df["job_title_short"] == "Business Analyst")]            # Confirmation

Empty DataFrame
Columns: [job_title_short, job_title, job_location, job_via, job_schedule_type, job_work_from_home, search_location, job_posted_date, job_no_degree_mention, job_health_insurance, job_country, salary_rate, salary_year_avg, salary_hour_avg, company_name, job_skills, job_type_skills]
Index: []

In [29]:
df.groupby(["job_title_short", "job_country"])["salary_year_avg"].sum()     # as we can see here there is no "Albania", because there is no value other than "Nan" there for "salary_year_avg" column: "Pandas will ignore Nan values and then ) is returned since no values remains"

job_title_short    job_country
Business Analyst   Argentina               1.422000e+05
                   Australia               2.630000e+05
                   Bangladesh              1.650000e+04
                   Belgium                 4.131000e+05
                   Bulgaria                2.959500e+05
                                               ...
Software Engineer  Ukraine                 5.400000e+04
                   United Arab Emirates    7.920000e+04
                   United Kingdom          5.164000e+05
                   United States           2.166049e+07
                   Vietnam                 1.072000e+05
Name: salary_year_avg, Length: 598, dtype: float64

In [34]:
df.groupby("job_title_short")[["salary_year_avg", "salary_hour_avg"]].mean()

                           salary_year_avg  salary_hour_avg
job_title_short
Business Analyst              91082.612833              NaN
Cloud Engineer               111268.453846              NaN
Data Analyst                  93841.907854              NaN
Data Engineer                130125.604250              NaN
Data Scientist               135988.837171              NaN
Machine Learning Engineer    126774.315972              NaN
Senior Data Analyst          113911.363665              NaN
Senior Data Engineer         145840.611624              NaN
Senior Data Scientist        154206.292996              NaN
Software Engineer            113393.760054              NaN

In [39]:
df.groupby("job_title_short")[["salary_year_avg", "salary_hour_avg"]].median()

                           salary_year_avg  salary_hour_avg
job_title_short
Business Analyst                   85000.0              NaN
Cloud Engineer                     90000.0              NaN
Data Analyst                       90000.0              NaN
Data Engineer                     125000.0              NaN
Data Scientist                    127500.0              NaN
Machine Learning Engineer         106415.0              NaN
Senior Data Analyst               111175.0              NaN
Senior Data Engineer              147500.0              NaN
Senior Data Scientist             155500.0              NaN
Software Engineer                  99150.0              NaN

In [33]:
df.groupby("job_title_short")[["salary_year_avg", "salary_hour_avg"]].count()

                           salary_year_avg  salary_hour_avg
job_title_short
Business Analyst                       610                0
Cloud Engineer                          65                0
Data Analyst                          5451                0
Data Engineer                         4500                0
Data Scientist                        5922                0
Machine Learning Engineer              576                0
Senior Data Analyst                   1131                0
Senior Data Engineer                  1591                0
Senior Data Scientist                 1690                0
Software Engineer                      467                0

In [43]:
df[df["salary_hour_avg"].notna()]       # proof

Empty DataFrame
Columns: [job_title_short, job_title, job_location, job_via, job_schedule_type, job_work_from_home, search_location, job_posted_date, job_no_degree_mention, job_health_insurance, job_country, salary_rate, salary_year_avg, salary_hour_avg, company_name, job_skills, job_type_skills]
Index: []

In [49]:
df.groupby(["job_title_short", "job_country"])[["salary_year_avg", "salary_hour_avg"]].sum()

                                        salary_year_avg  salary_hour_avg
job_title_short   job_country
Business Analyst  Argentina                1.422000e+05              0.0
                  Australia                2.630000e+05              0.0
                  Bangladesh               1.650000e+04              0.0
                  Belgium                  4.131000e+05              0.0
                  Bulgaria                 2.959500e+05              0.0
...                                                 ...              ...
Software Engineer Ukraine                  5.400000e+04              0.0
                  United Arab Emirates     7.920000e+04              0.0
                  United Kingdom           5.164000e+05              0.0
                  United States            2.166049e+07              0.0
                  Vietnam                  1.072000e+05              0.0

[598 rows x 2 columns]

In [52]:
# After removeing - df.dropna(subset="salary_year_avg", inplace=True) and replacing it with - df.dropna(subset="salary_year_avg") or reloading the dataframe

df.groupby(["job_title_short", "job_country"])[["salary_year_avg", "salary_hour_avg"]].sum()

                               salary_year_avg  salary_hour_avg
job_title_short   job_country
Business Analyst  Afghanistan              0.0              0.0
                  Albania                  0.0              0.0
                  Algeria                  0.0              0.0
                  Angola                   0.0              0.0
                  Argentina           142200.0              0.0
...                                        ...              ...
Software Engineer Venezuela                0.0              0.0
                  Vietnam             107200.0              0.0
                  Yemen                    0.0              0.0
                  Zambia                   0.0              0.0
                  Zimbabwe                 0.0              0.0

[1387 rows x 2 columns]

In [53]:
df.groupby(["job_title_short", "job_country"])[["salary_year_avg", "salary_hour_avg"]].mean()

                               salary_year_avg  salary_hour_avg
job_title_short   job_country
Business Analyst  Afghanistan              NaN              NaN
                  Albania                  NaN              NaN
                  Algeria                  NaN              NaN
                  Angola                   NaN              NaN
                  Argentina            71100.0              NaN
...                                        ...              ...
Software Engineer Venezuela                NaN              NaN
                  Vietnam              53600.0              NaN
                  Yemen                    NaN              NaN
                  Zambia                   NaN              NaN
                  Zimbabwe                 NaN              NaN

[1387 rows x 2 columns]

In [54]:
df.groupby(["job_title_short", "job_country"])[["salary_year_avg", "salary_hour_avg"]].median()

                               salary_year_avg  salary_hour_avg
job_title_short   job_country
Business Analyst  Afghanistan              NaN              NaN
                  Albania                  NaN              NaN
                  Algeria                  NaN              NaN
                  Angola                   NaN              NaN
                  Argentina            71100.0              NaN
...                                        ...              ...
Software Engineer Venezuela                NaN              NaN
                  Vietnam              53600.0              NaN
                  Yemen                    NaN              NaN
                  Zambia                   NaN              NaN
                  Zimbabwe                 NaN              NaN

[1387 rows x 2 columns]

In [55]:
df.groupby(["job_title_short", "job_country"])[["salary_year_avg", "salary_hour_avg"]].count()

                               salary_year_avg  salary_hour_avg
job_title_short   job_country
Business Analyst  Afghanistan                0                0
                  Albania                    0                0
                  Algeria                    0                0
                  Angola                     0                0
                  Argentina                  2                0
...                                        ...              ...
Software Engineer Venezuela                  0                0
                  Vietnam                    2                0
                  Yemen                      0                0
                  Zambia                     0                0
                  Zimbabwe                   0                0

[1387 rows x 2 columns]

In [58]:
# If we want to perform all the methods together
df.groupby(["job_title_short", "job_country"])[["salary_year_avg"]].agg(["min", "max", "mean", "median", "count"])

                              salary_year_avg
                                          min      max     mean   median count
job_title_short   job_country
Business Analyst  Afghanistan             NaN      NaN      NaN      NaN     0
                  Albania                 NaN      NaN      NaN      NaN     0
                  Algeria                 NaN      NaN      NaN      NaN     0
                  Angola                  NaN      NaN      NaN      NaN     0
                  Argentina           63000.0  79200.0  71100.0  71100.0     2
...                                       ...      ...      ...      ...   ...
Software Engineer Venezuela               NaN      NaN      NaN      NaN     0
                  Vietnam             28000.0  79200.0  53600.0  53600.0     2
                  Yemen                   NaN      NaN      NaN      NaN     0
                  Zambia                  NaN      NaN      NaN      NaN     0
                  Zimbabwe                NaN      NaN      NaN      NaN     0

[1387 rows x 5 columns]

In [59]:
df.groupby(["job_title_short", "job_country"])[["salary_year_avg", "salary_hour_avg"]].agg(["min", "max", "mean", "median", "count"])

                              salary_year_avg                             \
                                          min      max     mean   median
job_title_short   job_country
Business Analyst  Afghanistan             NaN      NaN      NaN      NaN
                  Albania                 NaN      NaN      NaN      NaN
                  Algeria                 NaN      NaN      NaN      NaN
                  Angola                  NaN      NaN      NaN      NaN
                  Argentina           63000.0  79200.0  71100.0  71100.0
...                                       ...      ...      ...      ...
Software Engineer Venezuela               NaN      NaN      NaN      NaN
                  Vietnam             28000.0  79200.0  53600.0  53600.0
                  Yemen                   NaN      NaN      NaN      NaN
                  Zambia                  NaN      NaN      NaN      NaN
                  Zimbabwe                NaN      NaN      NaN      NaN

                                    salary_hour_avg
                              count             min max mean median count
job_title_short   job_country
Business Analyst  Afghanistan     0             NaN NaN  NaN    NaN     0
                  Albania         0             NaN NaN  NaN    NaN     0
                  Algeria         0             NaN NaN  NaN    NaN     0
                  Angola          0             NaN NaN  NaN    NaN     0
                  Argentina       2             NaN NaN  NaN    NaN     0
...                             ...             ...  ..  ...    ...   ...
Software Engineer Venezuela       0             NaN NaN  NaN    NaN     0
                  Vietnam         2             NaN NaN  NaN    NaN     0
                  Yemen           0             NaN NaN  NaN    NaN     0
                  Zambia          0             NaN NaN  NaN    NaN     0
                  Zimbabwe        0             NaN NaN  NaN    NaN     0

[1387 rows x 10 columns]

In [60]:
df["job_country"]

0         United States
1                Mexico
2               Germany
3         United States
4                 Sudan
              ...
785736        Singapore
785737          Germany
785738         Malaysia
785739            Sudan
785740            India
Name: job_country, Length: 785741, dtype: str

In [61]:
df["job_country"].unique()

<ArrowStringArray>
[           'United States',                   'Mexico',
                  'Germany',                    'Sudan',
                  'Romania',                  'Denmark',
              'Switzerland',                   'France',
                   'Brazil',           'United Kingdom',
 ...
 'Northern Mariana Islands',                   'Angola',
                  'Somalia',         'Papua New Guinea',
                   'Gambia',                 'Djibouti',
                     'Laos',                  'Curaçao',
                 'Maldives',                   'Bhutan']
Length: 161, dtype: str

In [62]:
df["job_country"].value_counts()

job_country
United States               206292
India                        51088
United Kingdom               40375
France                       39922
Germany                      27694
                             ...
Northern Mariana Islands         4
Lesotho                          3
Mauritania                       3
Bhutan                           3
Maldives                         2
Name: count, Length: 160, dtype: int64

In [63]:
# top 20

df["job_country"].value_counts().head(20)

job_country
United States     206292
India              51088
United Kingdom     40375
France             39922
Germany            27694
Spain              25100
Singapore          23696
Sudan              21781
Netherlands        20631
Italy              17013
Canada             16029
Mexico             15139
Poland             14793
Portugal           14508
Australia          12955
South Africa       12414
Belgium            12078
Philippines        11786
Ireland            11162
Switzerland         9924
Name: count, dtype: int64

In [64]:
df["job_country"].isin(["Brazil"])

0         False
1         False
2         False
3         False
4         False
          ...
785736    False
785737    False
785738    False
785739    False
785740    False
Name: job_country, Length: 785741, dtype: bool

In [66]:
df["job_country"].isin(["Brazil"]).any()

np.True_

In [71]:
df[df["job_country"] == "Brazil"]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
14,Data Engineer,Data Engineer,"Rio de Janeiro, State of Rio de Janeiro, Brazil",via BeBee,Full-time,False,Brazil,2023-07-13 13:17:51,False,False,Brazil,NaN,NaN,NaN,Oowlish,"['mongodb', 'mongodb']","{'databases': ['mongodb'], 'programming': ['mo..."
55,Data Scientist,Data Scientist,"São Paulo, State of São Paulo, Brazil",via BeBee,Full-time,False,Brazil,2023-01-03 23:02:27,False,False,Brazil,NaN,NaN,NaN,Mars,"['python', 'sql', 'azure']","{'cloud': ['azure'], 'programming': ['python',..."
84,Data Scientist,Data Science,Brazil,via BeBee,Full-time,False,Brazil,2023-01-23 13:20:12,False,False,Brazil,NaN,NaN,NaN,Pfizer,"['python', 'r', 'sql', 'javascript', 'aws', 's...","{'cloud': ['aws', 'snowflake'], 'libraries': [..."
169,Data Analyst,Digital Analyst,Anywhere,via LinkedIn,Full-time and Contractor,True,Brazil,2023-12-05 13:10:20,True,False,Brazil,NaN,NaN,NaN,Acadia,"['firebase', 'firebase']","{'cloud': ['firebase'], 'databases': ['firebas..."
282,Data Engineer,Data Engineer,"Barueri, State of São Paulo, Brazil",via BeBee,Full-time,False,Brazil,2023-02-09 13:34:09,False,False,Brazil,NaN,NaN,NaN,Decision Group,"['nosql', 'java', 'python', 'scala', 'sql', 'a...","{'cloud': ['aws'], 'libraries': ['spark', 'had..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
784760,Software Engineer,MS Engineer,"São Paulo, State of São Paulo, Brazil",via Empregos Trabajo.org,Full-time,False,Brazil,2023-01-19 06:24:07,False,False,Brazil,NaN,NaN,NaN,NTT,['outlook'],{'analyst_tools': ['outlook']}
784968,Business Analyst,Communications and Reporting Analyst,Brazil,via Empregos Trabajo.org,Full-time,False,Brazil,2023-01-19 06:23:46,True,False,Brazil,NaN,NaN,NaN,PNUD Argentina,['sheets'],{'analyst_tools': ['sheets']}
785223,Senior Data Engineer,Data Engineer Sênior,"Indaiatuba, State of São Paulo, Brazil",via BeBee,Full-time,False,Brazil,2023-01-16 06:21:47,True,False,Brazil,NaN,NaN,NaN,GRUPO R1H1,"['python', 'sql', 'git']","{'other': ['git'], 'programming': ['python', '..."
785342,Machine Learning Engineer,Automation Engineer,"Belo Horizonte, State of Minas Gerais, Brazil",via BeBee,Full-time,False,Brazil,2023-01-18 06:23:26,False,False,Brazil,NaN,NaN,NaN,Worley,"['word', 'excel', 'powerpoint']","{'analyst_tools': ['word', 'excel', 'powerpoin..."
785556,Data Engineer,"API / Data Engineer (Python, PosgreSQL, API's,...","São Paulo, State of São Paulo, Brazil",via BeBee,Full-time,False,Brazil,2023-01-04 16:02:27,False,False,Brazil,NaN,NaN,NaN,Turing,"['python', 'postgresql', 'aws', 'redshift', 'f...","{'cloud': ['aws', 'redshift'], 'databases': ['..."

In [73]:
df[df["job_country"] == "Brazil"].count()

job_title_short          7032
job_title                7032
job_location             7032
job_via                  7032
job_schedule_type        7015
job_work_from_home       7032
search_location          7032
job_posted_date          7032
job_no_degree_mention    7032
job_health_insurance     7032
job_country              7032
salary_rate                68
salary_year_avg            61
salary_hour_avg             6
company_name             7031
job_skills               6190
job_type_skills          6190
dtype: int64

In [76]:
df["job_country"].isin(["India"]).any()

np.True_

In [77]:
df["job_country"].isin(["North Korea"]).any()

np.False_

In [80]:
uk_jobs = df[df["job_country"] == "United Kingdom"]

In [81]:
uk_jobs

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
15,Data Engineer,Data Engineer,"Aberdeen, UK",via LinkedIn,Temp work,False,United Kingdom,2023-10-19 13:37:16,False,False,United Kingdom,NaN,NaN,NaN,Orion Group,"['python', 'sql', 'power bi']","{'analyst_tools': ['power bi'], 'programming':..."
45,Senior Data Analyst,Senior Data Analyst,"Leeds, UK",via My Stateline Jobs,Full-time,False,United Kingdom,2023-05-30 13:14:08,True,False,United Kingdom,NaN,NaN,NaN,Corecom Consulting,"['sql', 'python']","{'programming': ['sql', 'python']}"
74,Data Analyst,Data Entry/Economic Data Analyst,"Worcester, UK",via BeBee,Full-time,False,United Kingdom,2023-11-01 13:11:18,False,False,United Kingdom,NaN,NaN,NaN,ttgTalentSolutions,"['sql', 'r', 'python', 'tableau', 'power bi']","{'analyst_tools': ['tableau', 'power bi'], 'pr..."
97,Data Analyst,"Systems & Data Analyst - Exploitation, Missing...",United Kingdom,via Totaljobs,Full-time and Contractor,False,United Kingdom,2023-12-04 13:14:01,True,False,United Kingdom,NaN,NaN,NaN,Solihull Metropolitan Borough Council,NaN,NaN
152,Data Scientist,Data Science Team Lead,Anywhere,via OnlyDataJobs,Full-time,True,United Kingdom,2023-12-23 13:12:16,False,False,United Kingdom,NaN,NaN,NaN,StepStone Group,"['react', 'docker']","{'libraries': ['react'], 'other': ['docker']}"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785485,Data Analyst,Data Quality Analyst,Anywhere,via LinkedIn,Full-time,True,United Kingdom,2023-10-04 06:09:44,False,False,United Kingdom,NaN,NaN,NaN,Viatris,"['sql', 'sql server', 'excel', 'powerpoint']","{'analyst_tools': ['excel', 'powerpoint'], 'da..."
785513,Data Scientist,Data Scientist,"Glasgow, UK",via Jobs Trabajo.org,Full-time,False,United Kingdom,2023-01-22 06:21:21,False,False,United Kingdom,NaN,NaN,NaN,ASA Recruitment,"['r', 'power bi']","{'analyst_tools': ['power bi'], 'programming':..."
785522,Data Engineer,Lead Data Engineer,"London, UK",via Jobs Trabajo.org,Full-time,False,United Kingdom,2023-01-19 06:16:45,True,False,United Kingdom,NaN,NaN,NaN,bionic-services-ltd,"['sql', 'python', 'sql server', 'aws', 'snowfl...","{'analyst_tools': ['ssis'], 'cloud': ['aws', '..."
785642,Data Engineer,Submission for the position: Data Engineer Sen...,"England, UK",via BAE Systems - Talentify,Full-time,False,United Kingdom,2023-01-02 06:31:23,True,False,United Kingdom,NaN,NaN,NaN,BAE Systems - UK,"['python', 'vue', 'ssis', 'ssrs', 'qlik', 'con...","{'analyst_tools': ['ssis', 'ssrs', 'qlik'], 'a..."
785676,Senior Data Scientist,Senior Data Scientist,"London, UK",via Jobs Trabajo.org,Full-time,False,United Kingdom,2023-01-22 06:21:23,False,False,United Kingdom,NaN,NaN,NaN,Department for International Development,"['r', 'python']","{'programming': ['r', 'python']}"

In [86]:
uk_jobs["job_title_short"].unique()

<ArrowStringArray>
[            'Data Engineer',       'Senior Data Analyst',
              'Data Analyst',            'Data Scientist',
     'Senior Data Scientist',      'Senior Data Engineer',
          'Business Analyst',         'Software Engineer',
 'Machine Learning Engineer',            'Cloud Engineer']
Length: 10, dtype: str

In [ ]:
uk_jobs.count()             # Like Overview

job_title_short          40375
job_title                40375
job_location             40361
job_via                  40375
job_schedule_type        40046
job_work_from_home       40375
search_location          40375
job_posted_date          40375
job_no_degree_mention    40375
job_health_insurance     40375
job_country              40375
salary_rate                290
salary_year_avg            287
salary_hour_avg              3
company_name             40375
job_skills               34126
job_type_skills          34126
dtype: int64

In [127]:
# More detailed information
uk_jobs.groupby("job_title_short").count()

,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_title_short,,,,,,,,,,,,,,,,
Business Analyst,5,5,5,5,5,5,5,5,5,5,5,5,0,5,3,3
Data Analyst,72,72,72,72,72,72,72,72,72,72,72,72,0,72,65,65
Data Engineer,60,60,60,60,60,60,60,60,60,60,60,60,0,60,59,59
Data Scientist,75,75,75,75,75,75,75,75,75,75,75,75,0,75,70,70
Machine Learning Engineer,7,7,7,7,7,7,7,7,7,7,7,7,0,7,6,6
Senior Data Analyst,8,8,8,8,8,8,8,8,8,8,8,8,0,8,7,7
Senior Data Engineer,24,24,24,24,24,24,24,24,24,24,24,24,0,24,24,24
Senior Data Scientist,31,31,31,31,31,31,31,31,31,31,31,31,0,31,31,31
Software Engineer,5,5,5,5,5,5,5,5,5,5,5,5,0,5,5,5

In [128]:
uk_jobs.groupby("job_title_short")["job_title_short"].count()       # More detailed information on job_title_short only

job_title_short
Business Analyst              5
Data Analyst                 72
Data Engineer                60
Data Scientist               75
Machine Learning Engineer     7
Senior Data Analyst           8
Senior Data Engineer         24
Senior Data Scientist        31
Software Engineer             5
Name: job_title_short, dtype: int64

In [130]:
#or
uk_jobs["job_title_short"].value_counts()

job_title_short
Data Scientist               75
Data Analyst                 72
Data Engineer                60
Senior Data Scientist        31
Senior Data Engineer         24
Senior Data Analyst           8
Machine Learning Engineer     7
Software Engineer             5
Business Analyst              5
Name: count, dtype: int64

In [94]:
uk_jobs[uk_jobs["salary_hour_avg"].isnull()]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
15,Data Engineer,Data Engineer,"Aberdeen, UK",via LinkedIn,Temp work,False,United Kingdom,2023-10-19 13:37:16,False,False,United Kingdom,NaN,NaN,NaN,Orion Group,"['python', 'sql', 'power bi']","{'analyst_tools': ['power bi'], 'programming':..."
45,Senior Data Analyst,Senior Data Analyst,"Leeds, UK",via My Stateline Jobs,Full-time,False,United Kingdom,2023-05-30 13:14:08,True,False,United Kingdom,NaN,NaN,NaN,Corecom Consulting,"['sql', 'python']","{'programming': ['sql', 'python']}"
74,Data Analyst,Data Entry/Economic Data Analyst,"Worcester, UK",via BeBee,Full-time,False,United Kingdom,2023-11-01 13:11:18,False,False,United Kingdom,NaN,NaN,NaN,ttgTalentSolutions,"['sql', 'r', 'python', 'tableau', 'power bi']","{'analyst_tools': ['tableau', 'power bi'], 'pr..."
97,Data Analyst,"Systems & Data Analyst - Exploitation, Missing...",United Kingdom,via Totaljobs,Full-time and Contractor,False,United Kingdom,2023-12-04 13:14:01,True,False,United Kingdom,NaN,NaN,NaN,Solihull Metropolitan Borough Council,NaN,NaN
152,Data Scientist,Data Science Team Lead,Anywhere,via OnlyDataJobs,Full-time,True,United Kingdom,2023-12-23 13:12:16,False,False,United Kingdom,NaN,NaN,NaN,StepStone Group,"['react', 'docker']","{'libraries': ['react'], 'other': ['docker']}"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785485,Data Analyst,Data Quality Analyst,Anywhere,via LinkedIn,Full-time,True,United Kingdom,2023-10-04 06:09:44,False,False,United Kingdom,NaN,NaN,NaN,Viatris,"['sql', 'sql server', 'excel', 'powerpoint']","{'analyst_tools': ['excel', 'powerpoint'], 'da..."
785513,Data Scientist,Data Scientist,"Glasgow, UK",via Jobs Trabajo.org,Full-time,False,United Kingdom,2023-01-22 06:21:21,False,False,United Kingdom,NaN,NaN,NaN,ASA Recruitment,"['r', 'power bi']","{'analyst_tools': ['power bi'], 'programming':..."
785522,Data Engineer,Lead Data Engineer,"London, UK",via Jobs Trabajo.org,Full-time,False,United Kingdom,2023-01-19 06:16:45,True,False,United Kingdom,NaN,NaN,NaN,bionic-services-ltd,"['sql', 'python', 'sql server', 'aws', 'snowfl...","{'analyst_tools': ['ssis'], 'cloud': ['aws', '..."
785642,Data Engineer,Submission for the position: Data Engineer Sen...,"England, UK",via BAE Systems - Talentify,Full-time,False,United Kingdom,2023-01-02 06:31:23,True,False,United Kingdom,NaN,NaN,NaN,BAE Systems - UK,"['python', 'vue', 'ssis', 'ssrs', 'qlik', 'con...","{'analyst_tools': ['ssis', 'ssrs', 'qlik'], 'a..."
785676,Senior Data Scientist,Senior Data Scientist,"London, UK",via Jobs Trabajo.org,Full-time,False,United Kingdom,2023-01-22 06:21:23,False,False,United Kingdom,NaN,NaN,NaN,Department for International Development,"['r', 'python']","{'programming': ['r', 'python']}"

In [95]:
uk_jobs = uk_jobs[uk_jobs["salary_year_avg"].notna()]

In [96]:
uk_jobs

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
1107,Data Scientist,"Data Scientist, Customer AI Engineering","London, UK",via Ai-Jobs.net,Full-time,False,United Kingdom,2023-06-20 13:12:50,False,False,United Kingdom,year,157500.0,NaN,Tractable,"['python', 'numpy', 'pandas', 'scikit-learn']","{'libraries': ['numpy', 'pandas', 'scikit-lear..."
2602,Data Analyst,Admin & Data Analyst,United Kingdom,via Ai-Jobs.net,Full-time,False,United Kingdom,2023-02-10 13:55:49,False,False,United Kingdom,year,51014.0,NaN,Catch22,"['excel', 'word', 'outlook']","{'analyst_tools': ['excel', 'word', 'outlook']}"
9778,Senior Data Analyst,Workday HCM Senior Data Analyst (18 month FTC),"London, UK",via Ai-Jobs.net,Contractor,False,United Kingdom,2023-07-10 13:36:15,True,False,United Kingdom,year,111175.0,NaN,WPP,"['vba', 'python', 'r', 'oracle', 'sap', 'excel']","{'analyst_tools': ['sap', 'excel'], 'cloud': [..."
9903,Senior Data Engineer,Senior Satellite Analytics Data Engineer,"Edinburgh, UK",via Ai-Jobs.net,Full-time,False,United Kingdom,2023-08-10 13:34:53,False,False,United Kingdom,year,147500.0,NaN,Verisk,"['python', 'sql', 'nosql', 'mongodb', 'mongodb...","{'cloud': ['aws'], 'databases': ['mongodb', 'e..."
13764,Data Scientist,Programmatic Data Specialist,"London, UK",via Ai-Jobs.net,Full-time,False,United Kingdom,2023-07-11 13:22:50,False,False,United Kingdom,year,109500.0,NaN,Publicis Groupe,"['excel', 'powerpoint', 'flow']","{'analyst_tools': ['excel', 'powerpoint'], 'ot..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
781461,Data Scientist,Data Scientist,"London, UK",via Ai-Jobs.net,Full-time,False,United Kingdom,2023-04-04 06:31:10,False,False,United Kingdom,year,88128.0,NaN,Kuda Technologies Ltd,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
783284,Senior Data Scientist,Senior Data Scientist,"Belfast, UK",via Ai-Jobs.net,Full-time,False,United Kingdom,2023-02-28 06:14:36,False,False,United Kingdom,year,157500.0,NaN,Axiom,"['sql', 'r', 'python', 'aws', 'redshift', 'spa...","{'async': ['jira', 'confluence'], 'cloud': ['a..."
783436,Data Scientist,Insight Analyst,"London, UK",via Ai-Jobs.net,Full-time,False,United Kingdom,2023-07-11 06:36:08,True,False,United Kingdom,year,72900.0,NaN,Xiatech,"['html', 'python', 'css', 'javascript', 'sql',...","{'analyst_tools': ['tableau'], 'async': ['jira..."
783598,Data Engineer,Data Engineer,"London, UK",via Ai-Jobs.net,Full-time,False,United Kingdom,2023-05-02 06:18:42,False,False,United Kingdom,year,96773.0,NaN,Prevail,"['python', 'java', 'scala', 'c#', 'r', 'redshi...","{'cloud': ['redshift', 'aws'], 'programming': ..."
783748,Data Engineer,Data Engineer,"Cambridge, UK",via Ai-Jobs.net,Full-time,False,United Kingdom,2023-07-22 06:16:12,False,False,United Kingdom,year,96773.0,NaN,Origin Sciences,"['python', 'sql', 'javascript', 'aws', 'pandas...","{'cloud': ['aws'], 'libraries': ['pandas'], 'o..."

In [97]:
uk_jobs[uk_jobs["salary_year_avg"].isnull()]

Empty DataFrame
Columns: [job_title_short, job_title, job_location, job_via, job_schedule_type, job_work_from_home, search_location, job_posted_date, job_no_degree_mention, job_health_insurance, job_country, salary_rate, salary_year_avg, salary_hour_avg, company_name, job_skills, job_type_skills]
Index: []

In [101]:
uk_jobs.groupby("job_title_short")["salary_year_avg"].count()       # Best Practice

job_title_short
Business Analyst              5
Data Analyst                 72
Data Engineer                60
Data Scientist               75
Machine Learning Engineer     7
Senior Data Analyst           8
Senior Data Engineer         24
Senior Data Scientist        31
Software Engineer             5
Name: salary_year_avg, dtype: int64

In [99]:
uk_jobs.groupby("job_title_short").count()

,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_title_short,,,,,,,,,,,,,,,,
Business Analyst,5,5,5,5,5,5,5,5,5,5,5,5,0,5,3,3
Data Analyst,72,72,72,72,72,72,72,72,72,72,72,72,0,72,65,65
Data Engineer,60,60,60,60,60,60,60,60,60,60,60,60,0,60,59,59
Data Scientist,75,75,75,75,75,75,75,75,75,75,75,75,0,75,70,70
Machine Learning Engineer,7,7,7,7,7,7,7,7,7,7,7,7,0,7,6,6
Senior Data Analyst,8,8,8,8,8,8,8,8,8,8,8,8,0,8,7,7
Senior Data Engineer,24,24,24,24,24,24,24,24,24,24,24,24,0,24,24,24
Senior Data Scientist,31,31,31,31,31,31,31,31,31,31,31,31,0,31,31,31
Software Engineer,5,5,5,5,5,5,5,5,5,5,5,5,0,5,5,5

In [100]:
uk_jobs.groupby("job_title_short").min()

,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_title_short,,,,,,,,,,,,,,,,
Business Analyst,Analyste en intelligence d'affaires (hybride)/...,"London, UK",via Ai-Jobs.net,Full-time,False,United Kingdom,2023-05-05 11:32:57,False,False,United Kingdom,year,30000.0,NaN,Fitch Group Inc P,"['sql', 'qlik', 'alteryx', 'power bi', 'tableau']","{'analyst_tools': ['qlik', 'alteryx', 'power b..."
Data Analyst,Admin & Data Analyst,"Aberdeen, UK",via Ai-Jobs.net,Contractor,False,United Kingdom,2023-01-06 07:28:48,False,False,United Kingdom,year,30000.0,NaN,AJ Bell,"['c', 'excel', 'tableau', 'outlook']","{'analyst_tools': ['dax'], 'libraries': ['gdpr..."
Data Engineer,AWS Data Engineer,Anywhere,via Agile Recruit,Contractor,False,United Kingdom,2023-01-11 00:30:57,False,False,United Kingdom,year,35000.0,NaN,AECOM,"['azure', 'aws', 'gcp', 'snowflake']","{'analyst_tools': ['excel'], 'cloud': ['aws', ..."
Data Scientist,Analytics Engineer,Anywhere,via Ai-Jobs.net,Contractor,False,United Kingdom,2023-01-02 09:26:47,False,False,United Kingdom,year,33488.5,NaN,2K,['aws'],"{'analyst_tools': ['alteryx', 'tableau', 'exce..."
Machine Learning Engineer,Deep Learning Research Engineer,"London, UK",via Ai-Jobs.net,Full-time,False,United Kingdom,2023-02-01 14:53:51,False,False,United Kingdom,year,85205.0,NaN,Checkout.com,"['go', 'python', 'jupyter']","{'cloud': ['aws'], 'libraries': ['spark', 'air..."
Senior Data Analyst,Data Operations Account Director,"Edinburgh, UK",via Ai-Jobs.net,Contractor,False,United Kingdom,2023-01-26 11:17:52,False,False,United Kingdom,year,79200.0,NaN,ClearScore,"['python', 'sql', 'postgresql', 'firebase', 'f...","{'analyst_tools': ['sap', 'excel'], 'cloud': [..."
Senior Data Engineer,Senior Big Data Engineer,"Brentford, UK",via Ai-Jobs.net,Full-time,False,United Kingdom,2023-01-07 05:29:06,False,False,United Kingdom,year,45000.0,NaN,Checkout.com,"['bash', 'git', 'jenkins']","{'analyst_tools': ['excel'], 'cloud': ['databr..."
Senior Data Scientist,Data Scientist / Senior Data Scientist,"Belfast, UK",via Ai-Jobs.net,Contractor,False,United Kingdom,2023-01-05 03:35:50,False,False,United Kingdom,year,72500.0,NaN,6point6,"['assembly', 'python', 'c', 'git', 'notion']","{'analyst_tools': ['excel'], 'cloud': ['aws'],..."
Software Engineer,Lead/Senior Software Engineer (Data Pipelines),"London, UK",via Ai-Jobs.net,Full-time,False,United Kingdom,2023-01-05 05:36:01,False,False,United Kingdom,year,89100.0,NaN,Isomorphic Labs,"['c++', 'linux', 'kubernetes', 'docker']","{'cloud': ['azure', 'aws'], 'libraries': ['air..."

In [102]:
uk_jobs.groupby("job_title_short")["salary_year_avg"].min()       # Best Practice

job_title_short
Business Analyst             30000.0
Data Analyst                 30000.0
Data Engineer                35000.0
Data Scientist               33488.5
Machine Learning Engineer    85205.0
Senior Data Analyst          79200.0
Senior Data Engineer         45000.0
Senior Data Scientist        72500.0
Software Engineer            89100.0
Name: salary_year_avg, dtype: float64

In [103]:
uk_jobs.groupby("job_title_short")[["salary_year_avg"]].min()       # Best Practice

                           salary_year_avg
job_title_short
Business Analyst                   30000.0
Data Analyst                       30000.0
Data Engineer                      35000.0
Data Scientist                     33488.5
Machine Learning Engineer          85205.0
Senior Data Analyst                79200.0
Senior Data Engineer               45000.0
Senior Data Scientist              72500.0
Software Engineer                  89100.0

In [104]:
uk_jobs.groupby(["job_title_short"])["salary_year_avg"].min()       # Best Practice

job_title_short
Business Analyst             30000.0
Data Analyst                 30000.0
Data Engineer                35000.0
Data Scientist               33488.5
Machine Learning Engineer    85205.0
Senior Data Analyst          79200.0
Senior Data Engineer         45000.0
Senior Data Scientist        72500.0
Software Engineer            89100.0
Name: salary_year_avg, dtype: float64

In [105]:
uk_jobs.groupby("job_title_short")["salary_year_avg"].agg(["min", "max", "count", "mean", "median"])

                               min       max  count           mean    median
job_title_short
Business Analyst           30000.0   73500.0      5   49560.000000   56700.0
Data Analyst               30000.0  180000.0     72   89410.916667   87750.0
Data Engineer              35000.0  249000.0     60  115622.200000  110000.0
Data Scientist             33488.5  205000.0     75  110250.933333  105300.0
Machine Learning Engineer  85205.0  200000.0      7  139564.428571  149653.0
Senior Data Analyst        79200.0  118140.0      8  107314.375000  111175.0
Senior Data Engineer       45000.0  171620.0     24  137550.020833  147500.0
Senior Data Scientist      72500.0  170575.0     31  129399.225806  157500.0
Software Engineer          89100.0  160000.0      5  103280.000000   89100.0

In [108]:
uk_jobs.groupby("job_title_short")["salary_year_avg"].agg(["min", "max", "count", "mean", "median"]).sort_values(by="median")

                               min       max  count           mean    median
job_title_short
Business Analyst           30000.0   73500.0      5   49560.000000   56700.0
Data Analyst               30000.0  180000.0     72   89410.916667   87750.0
Software Engineer          89100.0  160000.0      5  103280.000000   89100.0
Data Scientist             33488.5  205000.0     75  110250.933333  105300.0
Data Engineer              35000.0  249000.0     60  115622.200000  110000.0
Senior Data Analyst        79200.0  118140.0      8  107314.375000  111175.0
Senior Data Engineer       45000.0  171620.0     24  137550.020833  147500.0
Machine Learning Engineer  85205.0  200000.0      7  139564.428571  149653.0
Senior Data Scientist      72500.0  170575.0     31  129399.225806  157500.0

In [109]:
uk_jobs.groupby("job_title_short")["salary_year_avg"].agg(["min", "max", "count", "mean", "median"]).sort_values(by="median", ascending=False)

                               min       max  count           mean    median
job_title_short
Senior Data Scientist      72500.0  170575.0     31  129399.225806  157500.0
Machine Learning Engineer  85205.0  200000.0      7  139564.428571  149653.0
Senior Data Engineer       45000.0  171620.0     24  137550.020833  147500.0
Senior Data Analyst        79200.0  118140.0      8  107314.375000  111175.0
Data Engineer              35000.0  249000.0     60  115622.200000  110000.0
Data Scientist             33488.5  205000.0     75  110250.933333  105300.0
Software Engineer          89100.0  160000.0      5  103280.000000   89100.0
Data Analyst               30000.0  180000.0     72   89410.916667   87750.0
Business Analyst           30000.0   73500.0      5   49560.000000   56700.0

In [ ]:
uk_jobs.groupby("job_title_short")[["salary_year_avg"]].agg(["min", "max", "count", "mean", "median"]).sort_values(by="median")         # Error - [["salary_year_avg"]] is not Series it is an DataFrame, pandas check for column name - "median" which it will not find and throws an error

KeyError: 'median'

In [125]:
uk_jobs.groupby("job_title_short")[["salary_year_avg"]].agg(["min", "max", "count", "mean", "median"]).sort_values(by="job_title_short")   # Since the column  name "job_title_short" exists no Error!

                          salary_year_avg                                 \
                                      min       max count           mean
job_title_short
Business Analyst                  30000.0   73500.0     5   49560.000000
Data Analyst                      30000.0  180000.0    72   89410.916667
Data Engineer                     35000.0  249000.0    60  115622.200000
Data Scientist                    33488.5  205000.0    75  110250.933333
Machine Learning Engineer         85205.0  200000.0     7  139564.428571
Senior Data Analyst               79200.0  118140.0     8  107314.375000
Senior Data Engineer              45000.0  171620.0    24  137550.020833
Senior Data Scientist             72500.0  170575.0    31  129399.225806
Software Engineer                 89100.0  160000.0     5  103280.000000


                             median
job_title_short
Business Analyst            56700.0
Data Analyst                87750.0
Data Engineer              110000.0
Data Scientist             105300.0
Machine Learning Engineer  149653.0
Senior Data Analyst        111175.0
Senior Data Engineer       147500.0
Senior Data Scientist      157500.0
Software Engineer           89100.0

In [119]:
uk_jobs["job_title_short"].sort_values()

166572     Business Analyst
387745     Business Analyst
405777     Business Analyst
431877     Business Analyst
508380     Business Analyst
                ...
130904    Software Engineer
681531    Software Engineer
694137    Software Engineer
731081    Software Engineer
779691    Software Engineer
Name: job_title_short, Length: 287, dtype: str

In [121]:
uk_jobs[["job_title_short"]].sort_values()

TypeError: DataFrame.sort_values() missing 1 required positional argument: 'by'

In [123]:
uk_jobs[["job_title_short"]].sort_values(by="job_title_short")

          job_title_short
166572   Business Analyst
387745   Business Analyst
405777   Business Analyst
431877   Business Analyst
508380   Business Analyst
...                   ...
130904  Software Engineer
681531  Software Engineer
694137  Software Engineer
731081  Software Engineer
779691  Software Engineer

[287 rows x 1 columns]

In [117]:
uk_jobs.sort_values("job_title_short")

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
166572,Business Analyst,"Senior Director, Head of Business Intelligence",United Kingdom,via LinkedIn,Full-time,False,United Kingdom,2023-10-17 15:17:27,True,False,United Kingdom,year,30000.0,NaN,Humanity,NaN,NaN
387745,Business Analyst,Business Intelligence Specialist,United Kingdom,via Ai-Jobs.net,Full-time,False,United Kingdom,2023-12-10 18:13:03,True,False,United Kingdom,year,57600.0,NaN,Fitch Group Inc P,"['sql', 'qlik', 'alteryx', 'power bi', 'tableau']","{'analyst_tools': ['qlik', 'alteryx', 'power b..."
405777,Business Analyst,Business Intelligence Analyst,United Kingdom,via Ai-Jobs.net,Full-time,False,United Kingdom,2023-12-16 16:10:31,True,False,United Kingdom,year,73500.0,NaN,Globant,['ssis'],{'analyst_tools': ['ssis']}
431877,Business Analyst,Analyste en intelligence d'affaires (hybride)/...,United Kingdom,via LinkedIn,Full-time,False,United Kingdom,2023-11-19 16:15:05,True,False,United Kingdom,year,30000.0,NaN,Humanity,NaN,NaN
508380,Business Analyst,Senior Business Analyst - ESG - Data Products,"London, UK",via Ai-Jobs.net,Full-time,False,United Kingdom,2023-05-05 11:32:57,False,False,United Kingdom,year,56700.0,NaN,Verisk,"['word', 'excel', 'powerpoint', 'jira']","{'analyst_tools': ['word', 'excel', 'powerpoin..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130904,Software Engineer,Lead/Senior Software Engineer (Data Pipelines),"London, UK",via Ai-Jobs.net,Full-time,False,United Kingdom,2023-05-10 08:21:47,True,False,United Kingdom,year,89100.0,NaN,Our Future Health,"['java', 'python', 'scala', 'azure', 'aws', 'a...","{'cloud': ['azure', 'aws'], 'libraries': ['air..."
681531,Software Engineer,"Software Engineer, Market Data","London, UK",via LinkedIn,Full-time,False,United Kingdom,2023-11-17 10:16:02,True,False,United Kingdom,year,160000.0,NaN,Venture Search,"['c++', 'linux', 'kubernetes', 'docker']","{'os': ['linux'], 'other': ['kubernetes', 'doc..."
694137,Software Engineer,"Senior Software Engineer, Data Processing & Wo...","London, UK",via Ai-Jobs.net,Full-time,False,United Kingdom,2023-01-12 10:38:55,False,False,United Kingdom,year,89100.0,NaN,Reddit,"['go', 'python', 'java', 'scala', 'rust', 'c++...","{'libraries': ['kafka', 'spark', 'airflow'], '..."
731081,Software Engineer,MUFG 2024 UK Technology Analyst Programme: Arc...,United Kingdom,via Ai-Jobs.net,Full-time,False,United Kingdom,2023-11-02 21:17:04,False,False,United Kingdom,year,89100.0,NaN,MUFG,"['sql', 'oracle']","{'cloud': ['oracle'], 'programming': ['sql']}"
779691,Software Engineer,"Software Engineer (Machine Learning), London","London, UK",via Ai-Jobs.net,Full-time,False,United Kingdom,2023-01-05 05:36:01,False,False,United Kingdom,year,89100.0,NaN,Isomorphic Labs,"['python', 'java', 'c++', 'go', 'gcp', 'pytorc...","{'cloud': ['gcp'], 'libraries': ['pytorch', 't..."