# sample() = randomly pick some data from your DataFrame.

* sample(n=3): If we want a specific number of random rows, then we should use n.
* sample(frac=0.4): frac means fraction. Instead of saying how many rows we want, we say what proportion of the DataFrame we want
 
 Example :
Our DataFrame has 5 rows.

df.sample(frac=0.4)

0.4 = 40%.

So:

40% of 5 rows = 2 rows

Therefore, it randomly selects approximately 2 rows.

* df.sample(n=2, random_state=42): Using random_state=42 ensures that you get the same sample, 42 isn't special. we could use - random_state=10, random_state=100
* df.sample(n=3, replace=True): Normally, sample() selects rows without replacement, when set to "True" it means "Duplicates are allowed"
* df.sample(n=2, axis=1): Sampling columns, By default, sample() selects rows. "This randomly selects 2 columns"




df.sample(

    n=2,

    frac=None,

    replace=False,

    random_state=42,

    axis=0

)

In [1]:
import pandas as pd

data = {
    "Name": ["Asha", "Ravi", "John", "Priya", "Rahul"],
    "Age": [20, 21, 19, 22, 20],
    "Marks": [85, 90, 78, 95, 88]
}

df = pd.DataFrame(data)

print(df)

    Name  Age  Marks
0   Asha   20     85
1   Ravi   21     90
2   John   19     78
3  Priya   22     95
4  Rahul   20     88

In [3]:
df.sample()

   Name  Age  Marks
2  John   19     78

In [4]:
df.sample(n=3)

    Name  Age  Marks
4  Rahul   20     88
1   Ravi   21     90
3  Priya   22     95

In [5]:
df.sample(frac=0.4)

    Name  Age  Marks
4  Rahul   20     88
3  Priya   22     95

In [6]:
df.sample(n=3, replace=True)

   Name  Age  Marks
0  Asha   20     85
2  John   19     78
2  John   19     78

In [7]:
df.sample(n=3, random_state=42)

    Name  Age  Marks
1   Ravi   21     90
4  Rahul   20     88
2   John   19     78

In [8]:
df.sample(n=3, random_state=42)

    Name  Age  Marks
1   Ravi   21     90
4  Rahul   20     88
2   John   19     78

In [9]:
df.sample(n=3, random_state=42)

    Name  Age  Marks
1   Ravi   21     90
4  Rahul   20     88
2   John   19     78

In [10]:
df.sample(n=3)

    Name  Age  Marks
0   Asha   20     85
3  Priya   22     95
2   John   19     78

In [11]:
df.sample(n=3)

    Name  Age  Marks
4  Rahul   20     88
1   Ravi   21     90
2   John   19     78

In [12]:
df.sample(n=3)

   Name  Age  Marks
1  Ravi   21     90
2  John   19     78
0  Asha   20     85

In [13]:
df.sample(n=2, axis=1)

   Age   Name
0   20   Asha
1   21   Ravi
2   19   John
3   22  Priya
4   20  Rahul