In [58]:
import pandas as pd

In [143]:
from datasets import load_dataset


df = load_dataset("lukebarousse/data_jobs")["train"].to_pandas()

In [2]:
df.head()

        job_title_short  ...                                    job_type_skills
0  Senior Data Engineer  ...                                                NaN
1          Data Analyst  ...  {'analyst_tools': ['power bi', 'tableau'], 'pr...
2         Data Engineer  ...  {'analyst_tools': ['dax'], 'cloud': ['azure'],...
3         Data Engineer  ...  {'cloud': ['aws'], 'libraries': ['tensorflow',...
4         Data Engineer  ...  {'cloud': ['oracle', 'aws'], 'other': ['ansibl...

[5 rows x 17 columns]

In [18]:
df.head(10)

        job_title_short  ...                                    job_type_skills
0  Senior Data Engineer  ...                                                NaN
1          Data Analyst  ...  {'analyst_tools': ['power bi', 'tableau'], 'pr...
2         Data Engineer  ...  {'analyst_tools': ['dax'], 'cloud': ['azure'],...
3         Data Engineer  ...  {'cloud': ['aws'], 'libraries': ['tensorflow',...
4         Data Engineer  ...  {'cloud': ['oracle', 'aws'], 'other': ['ansibl...
5         Data Engineer  ...  {'cloud': ['gcp'], 'programming': ['python', '...
6  Senior Data Engineer  ...  {'cloud': ['gcp', 'bigquery'], 'databases': ['...
7         Data Engineer  ...  {'cloud': ['gcp', 'azure', 'aws', 'bigquery', ...
8      Business Analyst  ...  {'analyst_tools': ['excel', 'powerpoint', 'pow...
9        Data Scientist  ...  {'analyst_tools': ['excel'], 'cloud': ['azure'...

[10 rows x 17 columns]

In [3]:
df[["job_title_short", "job_title"]].head()

        job_title_short                                          job_title
0  Senior Data Engineer  Senior Clinical Data Engineer / Principal Clin...
1          Data Analyst                                       Data Analyst
2         Data Engineer  Data Engineer/Scientist/Analyst, Mid or Senior...
3         Data Engineer  LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...
4         Data Engineer                             Data Engineer- Sr Jobs

In [4]:
df.tail()

          job_title_short  ...                                    job_type_skills
785736  Software Engineer  ...  {'os': ['linux', 'unix'], 'other': ['kubernete...
785737       Data Analyst  ...  {'analyst_tools': ['sas', 'excel'], 'programmi...
785738   Business Analyst  ...         {'analyst_tools': ['powerpoint', 'excel']}
785739      Data Engineer  ...  {'cloud': ['aws', 'snowflake', 'azure', 'redsh...
785740  Software Engineer  ...              {'cloud': ['aws'], 'other': ['flow']}

[5 rows x 17 columns]

In [19]:
df.tail(10)

             job_title_short  ...                                    job_type_skills
785731         Data Engineer  ...  {'analyst_tools': ['excel'], 'cloud': ['aws', ...
785732         Data Engineer  ...  {'cloud': ['azure', 'databricks'], 'databases'...
785733     Software Engineer  ...                {'other': ['docker', 'kubernetes']}
785734      Business Analyst  ...                                {'os': ['windows']}
785735  Senior Data Engineer  ...  {'cloud': ['bigquery', 'aws'], 'libraries': ['...
785736     Software Engineer  ...  {'os': ['linux', 'unix'], 'other': ['kubernete...
785737          Data Analyst  ...  {'analyst_tools': ['sas', 'excel'], 'programmi...
785738      Business Analyst  ...         {'analyst_tools': ['powerpoint', 'excel']}
785739         Data Engineer  ...  {'cloud': ['aws', 'snowflake', 'azure', 'redsh...
785740     Software Engineer  ...              {'cloud': ['aws'], 'other': ['flow']}

[10 rows x 17 columns]

In [5]:
df[["job_title_short", "job_title"]].tail()

          job_title_short                                          job_title
785736  Software Engineer                                    DevOps Engineer
785737       Data Analyst                                   CRM Data Analyst
785738   Business Analyst                     Commercial Analyst - Start Now
785739      Data Engineer  Principal Associate, Data Engineer (Remote-Eli...
785740  Software Engineer                                 AWS System Analyst

In [7]:
df["job_title_short"] == "Data Analyst"

0         False
1          True
2         False
3         False
4         False
          ...
785736    False
785737     True
785738    False
785739    False
785740    False
Name: job_title_short, Length: 785741, dtype: bool

In [8]:
df[df["job_title_short"] == "Data Analyst"]

       job_title_short  ...                                    job_type_skills
1         Data Analyst  ...  {'analyst_tools': ['power bi', 'tableau'], 'pr...
12        Data Analyst  ...  {'analyst_tools': ['excel', 'power bi', 'sap']...
18        Data Analyst  ...  {'analyst_tools': ['excel', 'looker', 'tableau...
31        Data Analyst  ...                           {'programming': ['sql']}
34        Data Analyst  ...                         {'analyst_tools': ['sap']}
...                ...  ...                                                ...
785703    Data Analyst  ...                                                NaN
785705    Data Analyst  ...  {'analyst_tools': ['tableau'], 'programming': ...
785715    Data Analyst  ...                                                NaN
785717    Data Analyst  ...                        {'cloud': ['aws', 'azure']}
785737    Data Analyst  ...  {'analyst_tools': ['sas', 'excel'], 'programmi...

[196075 rows x 17 columns]

In [9]:
df[df["job_title_short"] == "Data Analyst"].count()

job_title_short          196075
job_title                196075
job_location             195801
job_via                  196067
job_schedule_type        191475
job_work_from_home       196075
search_location          196075
job_posted_date          196075
job_no_degree_mention    196075
job_health_insurance     196075
job_country              196067
salary_rate                9746
salary_year_avg            5451
salary_hour_avg            4138
company_name             196070
job_skills               159394
job_type_skills          159394
dtype: int64

In [20]:
df[df["job_title_short"] == "Data Analyst" and df["salary_year_avg"] > 1_00_000]            # Python's normal and expects one single True/False value, so we used "&" - bitwise operator

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [16]:
df[df["job_title_short"] == "Data Analyst" & df["salary_year_avg"] > 1_00_000]          # operator precedence, it starts trying to evaluate the expression involving & before the comparisons are completed.

TypeError: Cannot perform 'rand_' with a dtyped [float64] array and scalar of type [bool]

In [ ]:
df[(df["job_title_short"] == "Data Analyst") & (df["salary_year_avg"] > 100000)]

       job_title_short  ...                                    job_type_skills
410       Data Analyst  ...  {'analyst_tools': ['word', 'excel', 'visio', '...
1555      Data Analyst  ...  {'cloud': ['databricks'], 'libraries': ['spark']}
1681      Data Analyst  ...  {'analyst_tools': ['tableau', 'power bi', 'exc...
1684      Data Analyst  ...  {'cloud': ['azure', 'databricks'], 'os': ['lin...
1867      Data Analyst  ...  {'programming': ['php', 'python'], 'webframewo...
...                ...  ...                                                ...
783588    Data Analyst  ...  {'analyst_tools': ['excel'], 'libraries': ['ha...
783866    Data Analyst  ...                                   {'os': ['unix']}
784033    Data Analyst  ...         {'analyst_tools': ['power bi', 'tableau']}
785187    Data Analyst  ...  {'analyst_tools': ['looker'], 'programming': [...
785515    Data Analyst  ...                                                NaN

[1976 rows x 17 columns]

In [17]:
df[(df["job_title_short"] == "Data Analyst") & (df["salary_year_avg"] > 100000)].head()

     job_title_short  ...                                    job_type_skills
410     Data Analyst  ...  {'analyst_tools': ['word', 'excel', 'visio', '...
1555    Data Analyst  ...  {'cloud': ['databricks'], 'libraries': ['spark']}
1681    Data Analyst  ...  {'analyst_tools': ['tableau', 'power bi', 'exc...
1684    Data Analyst  ...  {'cloud': ['azure', 'databricks'], 'os': ['lin...
1867    Data Analyst  ...  {'programming': ['php', 'python'], 'webframewo...

[5 rows x 17 columns]

In [21]:
True & True

True

In [23]:
df[(df["job_title_short"] == "Data Analyst") & df["salary_year_avg"].notna()]

       job_title_short  ...                                    job_type_skills
109       Data Analyst  ...  {'analyst_tools': ['alteryx', 'tableau'], 'pro...
180       Data Analyst  ...         {'analyst_tools': ['excel', 'powerpoint']}
410       Data Analyst  ...  {'analyst_tools': ['word', 'excel', 'visio', '...
988       Data Analyst  ...  {'analyst_tools': ['excel', 'tableau'], 'progr...
1413      Data Analyst  ...  {'analyst_tools': ['excel', 'power bi'], 'prog...
...                ...  ...                                                ...
784033    Data Analyst  ...         {'analyst_tools': ['power bi', 'tableau']}
784423    Data Analyst  ...         {'analyst_tools': ['tableau', 'power bi']}
784882    Data Analyst  ...  {'analyst_tools': ['tableau', 'excel', 'altery...
785187    Data Analyst  ...  {'analyst_tools': ['looker'], 'programming': [...
785515    Data Analyst  ...                                                NaN

[5451 rows x 17 columns]

In [25]:
df[(df["job_title_short"] == "Data Analyst") & df["salary_year_avg"].notna()].count()

job_title_short          5451
job_title                5451
job_location             5372
job_via                  5451
job_schedule_type        5443
job_work_from_home       5451
search_location          5451
job_posted_date          5451
job_no_degree_mention    5451
job_health_insurance     5451
job_country              5451
salary_rate              5451
salary_year_avg          5451
salary_hour_avg             0
company_name             5451
job_skills               4845
job_type_skills          4845
dtype: int64

In [26]:
df[(df["job_title_short"] == "Data Analyst") & df["salary_year_avg"].notna()].head()

     job_title_short  ...                                    job_type_skills
109     Data Analyst  ...  {'analyst_tools': ['alteryx', 'tableau'], 'pro...
180     Data Analyst  ...         {'analyst_tools': ['excel', 'powerpoint']}
410     Data Analyst  ...  {'analyst_tools': ['word', 'excel', 'visio', '...
988     Data Analyst  ...  {'analyst_tools': ['excel', 'tableau'], 'progr...
1413    Data Analyst  ...  {'analyst_tools': ['excel', 'power bi'], 'prog...

[5 rows x 17 columns]

In [27]:
df[(df["job_title_short"] == "Data Analyst") & df["salary_year_avg"].notna()].tail()

       job_title_short  ...                                    job_type_skills
784033    Data Analyst  ...         {'analyst_tools': ['power bi', 'tableau']}
784423    Data Analyst  ...         {'analyst_tools': ['tableau', 'power bi']}
784882    Data Analyst  ...  {'analyst_tools': ['tableau', 'excel', 'altery...
785187    Data Analyst  ...  {'analyst_tools': ['looker'], 'programming': [...
785515    Data Analyst  ...                                                NaN

[5 rows x 17 columns]

# df.info()

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  str
 1   job_title              785740 non-null  str
 2   job_location           784696 non-null  str
 3   job_via                785733 non-null  str
 4   job_schedule_type      773074 non-null  str
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  str
 7   job_posted_date        785741 non-null  str
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  str
 11  salary_rate            33067 non-null   str
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  str
 15  job_skills             668704 non-null  str
 16  job_type_skills        668704 non-null  str
dtypes: bool(3), float64(2), str(12)
memory usage: 279.3 MB

In [29]:
# or

In [30]:
df.columns

Index(['job_title_short', 'job_title', 'job_location', 'job_via',
       'job_schedule_type', 'job_work_from_home', 'search_location',
       'job_posted_date', 'job_no_degree_mention', 'job_health_insurance',
       'job_country', 'salary_rate', 'salary_year_avg', 'salary_hour_avg',
       'company_name', 'job_skills', 'job_type_skills'],
      dtype='str')

In [31]:
df.shape

(785741, 17)

In [32]:
df.index

RangeIndex(start=0, stop=785741, step=1)

In [33]:
len(df)

785741

In [34]:
df.count()

job_title_short          785741
job_title                785740
job_location             784696
job_via                  785733
job_schedule_type        773074
job_work_from_home       785741
search_location          785741
job_posted_date          785741
job_no_degree_mention    785741
job_health_insurance     785741
job_country              785692
salary_rate               33067
salary_year_avg           22003
salary_hour_avg           10662
company_name             785723
job_skills               668704
job_type_skills          668704
dtype: int64

# df.describe()

In [35]:
df.describe()

       salary_year_avg  salary_hour_avg
count     22003.000000     10662.000000
mean     123286.274072        47.016598
std       48312.449482        21.890738
min       15000.000000         8.000000
25%       90000.000000        27.500000
50%      115000.000000        45.980000
75%      150000.000000        61.159996
max      960000.000000       391.000000

# df.iloc[start_index, end_index]   - int location

In [39]:
df.iloc[0:5]

        job_title_short  ...                                    job_type_skills
0  Senior Data Engineer  ...                                                NaN
1          Data Analyst  ...  {'analyst_tools': ['power bi', 'tableau'], 'pr...
2         Data Engineer  ...  {'analyst_tools': ['dax'], 'cloud': ['azure'],...
3         Data Engineer  ...  {'cloud': ['aws'], 'libraries': ['tensorflow',...
4         Data Engineer  ...  {'cloud': ['oracle', 'aws'], 'other': ['ansibl...

[5 rows x 17 columns]

In [40]:
df.iloc[1:6:2]

  job_title_short  ...                                    job_type_skills
1    Data Analyst  ...  {'analyst_tools': ['power bi', 'tableau'], 'pr...
3   Data Engineer  ...  {'cloud': ['aws'], 'libraries': ['tensorflow',...
5   Data Engineer  ...  {'cloud': ['gcp'], 'programming': ['python', '...

[3 rows x 17 columns]

In [41]:
df.iloc[90:101]

          job_title_short  ...                                    job_type_skills
90         Data Scientist  ...  {'analyst_tools': ['tableau'], 'libraries': ['...
91         Data Scientist  ...  {'analyst_tools': ['excel', 'tableau'], 'libra...
92          Data Engineer  ...                 {'programming': ['sql', 'python']}
93           Data Analyst  ...  {'analyst_tools': ['power bi', 'excel', 'word'...
94          Data Engineer  ...  {'analyst_tools': ['power bi', 'tableau'], 'cl...
95          Data Engineer  ...  {'analyst_tools': ['tableau'], 'databases': ['...
96          Data Engineer  ...  {'analyst_tools': ['sap'], 'cloud': ['azure', ...
97           Data Analyst  ...                                                NaN
98   Senior Data Engineer  ...  {'cloud': ['aws', 'databricks'], 'libraries': ...
99          Data Engineer  ...  {'libraries': ['react', 'spark', 'hadoop'], 'o...
100        Data Scientist  ...  {'programming': ['sql', 'r', 'python'], 'webfr...

[11 rows x 17 columns]

In [48]:
df["job_title_short"].iloc[1:6]

1     Data Analyst
2    Data Engineer
3    Data Engineer
4    Data Engineer
5    Data Engineer
Name: job_title_short, dtype: str

In [49]:
df[["job_title_short"]].loc[1:6]

        job_title_short
1          Data Analyst
2         Data Engineer
3         Data Engineer
4         Data Engineer
5         Data Engineer
6  Senior Data Engineer

In [50]:
df[["job_title_short", "job_title"]]

             job_title_short                                          job_title
0       Senior Data Engineer  Senior Clinical Data Engineer / Principal Clin...
1               Data Analyst                                       Data Analyst
2              Data Engineer  Data Engineer/Scientist/Analyst, Mid or Senior...
3              Data Engineer  LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...
4              Data Engineer                             Data Engineer- Sr Jobs
...                      ...                                                ...
785736     Software Engineer                                    DevOps Engineer
785737          Data Analyst                                   CRM Data Analyst
785738      Business Analyst                     Commercial Analyst - Start Now
785739         Data Engineer  Principal Associate, Data Engineer (Remote-Eli...
785740     Software Engineer                                 AWS System Analyst

[785741 rows x 2 columns]

In [ ]:
df[["job_title_short", "job_title"]].loc[1:6]

        job_title_short                                          job_title
1          Data Analyst                                       Data Analyst
2         Data Engineer  Data Engineer/Scientist/Analyst, Mid or Senior...
3         Data Engineer  LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...
4         Data Engineer                             Data Engineer- Sr Jobs
5         Data Engineer                                  GCP Data Engineer
6  Senior Data Engineer                  Senior Data Engineer  - GCP Cloud

# .unique()

In [119]:
df["job_title_short"].unique()

<ArrowStringArray>
[     'Senior Data Engineer',              'Data Analyst',
             'Data Engineer',          'Business Analyst',
            'Data Scientist', 'Machine Learning Engineer',
       'Senior Data Analyst',            'Cloud Engineer',
     'Senior Data Scientist',         'Software Engineer']
Length: 10, dtype: str

In [53]:
df.unique()

AttributeError: 'DataFrame' object has no attribute 'unique'

In [54]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  str
 1   job_title              785740 non-null  str
 2   job_location           784696 non-null  str
 3   job_via                785733 non-null  str
 4   job_schedule_type      773074 non-null  str
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  str
 7   job_posted_date        785741 non-null  str
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  str
 11  salary_rate            33067 non-null   str
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  str
 15  job_skills             668704 non-null  str
 16  job_type_skills        668704 non-null  str
dtypes: bool(3), float64(2), str(12)
memory usage: 279.3 MB

In [55]:
type(df["job_posted_date"])

pandas.Series

In [56]:
type(df["job_posted_date"][0])

str

In [59]:
df["job_posted_date"] = pd.to_datetime(df["job_posted_date"])

In [60]:
type(df["job_posted_date"])

pandas.Series

In [70]:
type(df["job_posted_date"][0])

pandas.Timestamp

In [62]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  str
 1   job_title              785740 non-null  str
 2   job_location           784696 non-null  str
 3   job_via                785733 non-null  str
 4   job_schedule_type      773074 non-null  str
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  str
 7   job_posted_date        785741 non-null  datetime64[us]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  str
 11  salary_rate            33067 non-null   str
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  str
 15  job_skills             668704 non-null  str
 16  job_type_skills        668704 non-null  str
dtypes: bool(3), datetime64[us](1), float64(2), str(11)
memory usage: 265.1 MB

In [66]:
# or

df["job_posted_date"] = pd.to_datetime(df.job_posted_date)

In [69]:
# or

df.job_posted_date = pd.to_datetime(df["job_posted_date"])

In [71]:
df["job_posted_date"].dt.month

0          6
1          1
2         10
3          7
4          8
          ..
785736     3
785737     3
785738     3
785739     3
785740     3
Name: job_posted_date, Length: 785741, dtype: int32

In [73]:
df[["job_posted_date"]].dt.month        # returns a DataFrame, not a Series. And .dt is an accessor for a datetime Series, not for the whole DataFrame.

AttributeError: 'DataFrame' object has no attribute 'dt'

In [101]:
df["job_posted_month"] = df["job_posted_date"].dt.month

In [78]:
df.head()

        job_title_short  ... job_posted_month
0  Senior Data Engineer  ...                6
1          Data Analyst  ...                1
2         Data Engineer  ...               10
3         Data Engineer  ...                7
4         Data Engineer  ...                8

[5 rows x 18 columns]

In [79]:
df["job_posted_month"]

0          6
1          1
2         10
3          7
4          8
          ..
785736     3
785737     3
785738     3
785739     3
785740     3
Name: job_posted_month, Length: 785741, dtype: int32

In [80]:
df[["job_posted_month"]]

        job_posted_month
0                      6
1                      1
2                     10
3                      7
4                      8
...                  ...
785736                 3
785737                 3
785738                 3
785739                 3
785740                 3

[785741 rows x 1 columns]

In [81]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 18 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  str
 1   job_title              785740 non-null  str
 2   job_location           784696 non-null  str
 3   job_via                785733 non-null  str
 4   job_schedule_type      773074 non-null  str
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  str
 7   job_posted_date        785741 non-null  datetime64[us]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  str
 11  salary_rate            33067 non-null   str
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  str
 15  job_skills             668704 non-null  str
 16  job_type_skills        668704 non-null  str
 17  job_posted_month       785741 non-null  int32
dtypes: bool(3), datetime64[us](1), float64(2), int32(1), str(11)
memory usage: 268.1 MB

In [82]:
df.sort_values(df["job_posted_date"])

KeyError: 0        2023-06-16 13:44:15
1        2023-01-14 13:18:07
2        2023-10-10 13:14:55
3        2023-07-04 13:01:41
4        2023-08-07 14:29:36
                 ...
785736   2023-03-13 06:16:16
785737   2023-03-12 06:18:18
785738   2023-03-12 06:32:36
785739   2023-03-12 06:32:15
785740   2023-03-13 06:16:31
Name: job_posted_date, Length: 785741, dtype: datetime64[us]

In [84]:
help(df.sort_values)

Help on method sort_values in module pandas.core.frame:

sort_values(
    by: IndexLabel,
    *,
    axis: Axis = 0,
    ascending: bool | list[bool] | tuple[bool, ...] = True,
    inplace: bool = False,
    kind: SortKind = 'quicksort',
    na_position: str = 'last',
    ignore_index: bool = False,
    key: ValueKeyFunc | None = None
) -> DataFrame | None method of pandas.DataFrame instance
    Sort by the values along either axis.

    Parameters
    ----------
    by : str or list of str
        Name or list of names to sort by.

        - if `axis` is 0 or `'index'` then `by` may contain index
          levels and/or column labels.
        - if `axis` is 1 or `'columns'` then `by` may contain column
          levels and/or index labels.
    axis : "{0 or 'index', 1 or 'columns'}", default 0
         Axis to be sorted.
    ascending : bool or list of bool, default True
         Sort ascending vs. descending. Specify list for multiple sort
         orders.  If this is a list of bools, must match the length of
         the by.
    inplace : bool, default False
         If True, perform operation in-place.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, default 'quicksort'
         Choice of sorting algorithm. See also :func:`numpy.sort` for more
         information. `mergesort` and `stable` are the only stable algorithms. For
         DataFrames, this option is only applied when sorting on a single
         column or label.
    na_position : {'first', 'last'}, default 'last'
         Puts NaNs at the beginning if `first`; `last` puts NaNs at the
         end.
    ignore_index : bool, default False
         If True, the resulting axis will be labeled 0, 1, …, n - 1.
    key : callable, optional
        Apply the key function to the values
        before sorting. This is similar to the `key` argument in the
        builtin :meth:`sorted` function, with the notable difference that
        this `key` function should be *vectorized*. It should expect a
        ``Series`` and return a Series with the same shape as the input.
        It will be applied to each column in `by` independently. The values in the
        returned Series will be used as the keys for sorting.

    Returns
    -------
    DataFrame or None
        DataFrame with sorted values or None if ``inplace=True``.

    See Also
    --------
    DataFrame.sort_index : Sort a DataFrame by the index.
    Series.sort_values : Similar method for a Series.

    Examples
    --------
    >>> df = pd.DataFrame(
    ...     {
    ...         "col1": ["A", "A", "B", np.nan, "D", "C"],
    ...         "col2": [2, 1, 9, 8, 7, 4],
    ...         "col3": [0, 1, 9, 4, 2, 3],
    ...         "col4": ["a", "B", "c", "D", "e", "F"],
    ...     }
    ... )
    >>> df
      col1  col2  col3 col4
    0    A     2     0    a
    1    A     1     1    B
    2    B     9     9    c
    3  NaN     8     4    D
    4    D     7     2    e
    5    C     4     3    F

    **Sort by a single column**

    In this case, we are sorting the rows according to values in ``col1``:

    >>> df.sort_values(by=["col1"])
      col1  col2  col3 col4
    0    A     2     0    a
    1    A     1     1    B
    2    B     9     9    c
    5    C     4     3    F
    4    D     7     2    e
    3  NaN     8     4    D

    **Sort by multiple columns**

    You can also provide multiple columns to ``by`` argument, as shown below.
    In this example, the rows are first sorted according to ``col1``, and then
    the rows that have an identical value in ``col1`` are sorted according
    to ``col2``.

    >>> df.sort_values(by=["col1", "col2"])
      col1  col2  col3 col4
    1    A     1     1    B
    0    A     2     0    a
    2    B     9     9    c
    5    C     4     3    F
    4    D     7     2    e
    3  NaN     8     4    D

    **Sort in a descending order**

    The sort order can be reversed using ``ascending`` argument, as shown below:

    >>> df.sort_values(by="col1", ascending=False)
      col1  col2  col3 col4
    4    D     7     2    e
    5    C     4     3    F
    2    B     9     9    c
    0    A     2     0    a
    1    A     1     1    B
    3  NaN     8     4    D

    **Placing any** ``NA`` **first**

    Note that in the above example, the rows that contain an ``NA`` value in their
    ``col1`` are placed at the end of the dataframe. This behavior can be modified
    via ``na_position`` argument, as shown below:

    >>> df.sort_values(by="col1", ascending=False, na_position="first")
      col1  col2  col3 col4
    3  NaN     8     4    D
    4    D     7     2    e
    5    C     4     3    F
    2    B     9     9    c
    0    A     2     0    a
    1    A     1     1    B

    **Customized sort order**

    The ``key`` argument allows for a further customization of sorting behaviour.
    For example, you may want
    to ignore the `letter's case <https://en.wikipedia.org/wiki/Letter_case>`__
    when sorting strings:

    >>> df.sort_values(by="col4", key=lambda col: col.str.lower())
       col1  col2  col3 col4
    0    A     2     0    a
    1    A     1     1    B
    2    B     9     9    c
    3  NaN     8     4    D
    4    D     7     2    e
    5    C     4     3    F

    Another typical example is
    `natural sorting <https://en.wikipedia.org/wiki/Natural_sort_order>`__.
    This can be done using
    ``natsort`` `package <https://github.com/SethMMorton/natsort>`__,
    which provides a function to generate a key
    to sort data in their natural order:

    >>> df = pd.DataFrame(
    ...     {
    ...         "hours": ["0hr", "128hr", "0hr", "64hr", "64hr", "128hr"],
    ...         "mins": [
    ...             "10mins",
    ...             "40mins",
    ...             "40mins",
    ...             "40mins",
    ...             "10mins",
    ...             "10mins",
    ...         ],
    ...         "value": [10, 20, 30, 40, 50, 60],
    ...     }
    ... )
    >>> df
       hours    mins  value
    0    0hr  10mins     10
    1  128hr  40mins     20
    2    0hr  40mins     30
    3   64hr  40mins     40
    4   64hr  10mins     50
    5  128hr  10mins     60
    >>> from natsort import natsort_keygen
    >>> df.sort_values(
    ...     by=["hours", "mins"],
    ...     key=natsort_keygen(),
    ... )
       hours    mins  value
    0    0hr  10mins     10
    2    0hr  40mins     30
    4   64hr  10mins     50
    3   64hr  40mins     40
    5  128hr  10mins     60
    1  128hr  40mins     20

In [85]:
df.sort_values("job_posted_date")

                  job_title_short  ... job_posted_month
108804               Data Analyst  ...                1
96906                Data Analyst  ...                1
98438                Data Analyst  ...                1
110290               Data Analyst  ...                1
72158         Senior Data Analyst  ...                1
...                           ...  ...              ...
362129              Data Engineer  ...               12
351830              Data Engineer  ...               12
327439              Data Engineer  ...               12
112373        Senior Data Analyst  ...               12
90102   Machine Learning Engineer  ...               12

[785741 rows x 18 columns]

In [86]:
df

             job_title_short  ... job_posted_month
0       Senior Data Engineer  ...                6
1               Data Analyst  ...                1
2              Data Engineer  ...               10
3              Data Engineer  ...                7
4              Data Engineer  ...                8
...                      ...  ...              ...
785736     Software Engineer  ...                3
785737          Data Analyst  ...                3
785738      Business Analyst  ...                3
785739         Data Engineer  ...                3
785740     Software Engineer  ...                3

[785741 rows x 18 columns]

In [113]:
df = df.sort_values("job_posted_date")

# or

df.sort_values("job_posted_date", ascending = True, inplace = True)

# or

df.sort_values(by=["job_posted_date", "job_posted_month"], inplace = True)        # Best Practice

In [114]:
df

                  job_title_short  ... job_posted_month
108804               Data Analyst  ...                1
96906                Data Analyst  ...                1
98438                Data Analyst  ...                1
110290               Data Analyst  ...                1
72158         Senior Data Analyst  ...                1
...                           ...  ...              ...
362129              Data Engineer  ...               12
351830              Data Engineer  ...               12
327439              Data Engineer  ...               12
112373        Senior Data Analyst  ...               12
90102   Machine Learning Engineer  ...               12

[785741 rows x 18 columns]

In [107]:
# For columns .drop(column_name)

df.drop(labels="job_posted_month", axis=1)     # Best Practice    # axis = 1 (for columns) and axis = 0 for rows


# or


df.drop("job_posted_month", axis=1)

                  job_title_short  ...                                    job_type_skills
108804               Data Analyst  ...  {'analyst_tools': ['visio'], 'async': ['jira',...
96906                Data Analyst  ...  {'analyst_tools': ['sas'], 'programming': ['sq...
98438                Data Analyst  ...  {'analyst_tools': ['tableau', 'excel'], 'cloud...
110290               Data Analyst  ...        {'async': ['jira'], 'programming': ['sql']}
72158         Senior Data Analyst  ...  {'async': ['jira'], 'other': ['atlassian'], 'p...
...                           ...  ...                                                ...
351830              Data Engineer  ...  {'analyst_tools': ['power bi', 'word'], 'cloud...
362129              Data Engineer  ...  {'cloud': ['snowflake'], 'libraries': ['airflo...
327439              Data Engineer  ...  {'other': ['kubernetes'], 'webframeworks': ['e...
112373        Senior Data Analyst  ...  {'analyst_tools': ['tableau', 'power bi'], 'li...
90102   Machine Learning Engineer  ...                                                NaN

[785741 rows x 17 columns]

In [93]:
df

                  job_title_short  ... job_posted_month
108804               Data Analyst  ...                1
96906                Data Analyst  ...                1
98438                Data Analyst  ...                1
110290               Data Analyst  ...                1
72158         Senior Data Analyst  ...                1
...                           ...  ...              ...
351830              Data Engineer  ...               12
362129              Data Engineer  ...               12
327439              Data Engineer  ...               12
112373        Senior Data Analyst  ...               12
90102   Machine Learning Engineer  ...               12

[785741 rows x 18 columns]

In [95]:
df.drop("job_posted_month", axis=1, inplace=True)

In [96]:
df

                  job_title_short  ...                                    job_type_skills
108804               Data Analyst  ...  {'analyst_tools': ['visio'], 'async': ['jira',...
96906                Data Analyst  ...  {'analyst_tools': ['sas'], 'programming': ['sq...
98438                Data Analyst  ...  {'analyst_tools': ['tableau', 'excel'], 'cloud...
110290               Data Analyst  ...        {'async': ['jira'], 'programming': ['sql']}
72158         Senior Data Analyst  ...  {'async': ['jira'], 'other': ['atlassian'], 'p...
...                           ...  ...                                                ...
351830              Data Engineer  ...  {'analyst_tools': ['power bi', 'word'], 'cloud...
362129              Data Engineer  ...  {'cloud': ['snowflake'], 'libraries': ['airflo...
327439              Data Engineer  ...  {'other': ['kubernetes'], 'webframeworks': ['e...
112373        Senior Data Analyst  ...  {'analyst_tools': ['tableau', 'power bi'], 'li...
90102   Machine Learning Engineer  ...                                                NaN

[785741 rows x 17 columns]

In [99]:
# or rows .drop(index)

df.drop(108804, axis=0)

                  job_title_short  ...                                    job_type_skills
96906                Data Analyst  ...  {'analyst_tools': ['sas'], 'programming': ['sq...
98438                Data Analyst  ...  {'analyst_tools': ['tableau', 'excel'], 'cloud...
110290               Data Analyst  ...        {'async': ['jira'], 'programming': ['sql']}
72158         Senior Data Analyst  ...  {'async': ['jira'], 'other': ['atlassian'], 'p...
104526               Data Analyst  ...                       {'analyst_tools': ['excel']}
...                           ...  ...                                                ...
351830              Data Engineer  ...  {'analyst_tools': ['power bi', 'word'], 'cloud...
362129              Data Engineer  ...  {'cloud': ['snowflake'], 'libraries': ['airflo...
327439              Data Engineer  ...  {'other': ['kubernetes'], 'webframeworks': ['e...
112373        Senior Data Analyst  ...  {'analyst_tools': ['tableau', 'power bi'], 'li...
90102   Machine Learning Engineer  ...                                                NaN

[785740 rows x 17 columns]

In [102]:
# More easy

df.drop(columns="job_posted_month")

                  job_title_short  ...                                    job_type_skills
108804               Data Analyst  ...  {'analyst_tools': ['visio'], 'async': ['jira',...
96906                Data Analyst  ...  {'analyst_tools': ['sas'], 'programming': ['sq...
98438                Data Analyst  ...  {'analyst_tools': ['tableau', 'excel'], 'cloud...
110290               Data Analyst  ...        {'async': ['jira'], 'programming': ['sql']}
72158         Senior Data Analyst  ...  {'async': ['jira'], 'other': ['atlassian'], 'p...
...                           ...  ...                                                ...
351830              Data Engineer  ...  {'analyst_tools': ['power bi', 'word'], 'cloud...
362129              Data Engineer  ...  {'cloud': ['snowflake'], 'libraries': ['airflo...
327439              Data Engineer  ...  {'other': ['kubernetes'], 'webframeworks': ['e...
112373        Senior Data Analyst  ...  {'analyst_tools': ['tableau', 'power bi'], 'li...
90102   Machine Learning Engineer  ...                                                NaN

[785741 rows x 17 columns]

In [110]:
# If we want to drop the list of columns

df.drop(columns=["job_title_short", "job_title"])

                  job_location  ... job_posted_month
108804            New York, NY  ...                1
96906           Bloomfield, CT  ...                1
98438           Washington, DC  ...                1
110290             Fairfax, VA  ...                1
72158            Worcester, MA  ...                1
...                        ...  ...              ...
351830       San Francisco, CA  ...               12
362129           Sunnyvale, CA  ...               12
327439          Southfield, MI  ...               12
112373  Boston, MA  (+1 other)  ...               12
90102               Boston, MA  ...               12

[785741 rows x 16 columns]

In [112]:
df.dropna(subset="job_title_short")

                  job_title_short  ... job_posted_month
108804               Data Analyst  ...                1
96906                Data Analyst  ...                1
98438                Data Analyst  ...                1
110290               Data Analyst  ...                1
72158         Senior Data Analyst  ...                1
...                           ...  ...              ...
362129              Data Engineer  ...               12
351830              Data Engineer  ...               12
327439              Data Engineer  ...               12
112373        Senior Data Analyst  ...               12
90102   Machine Learning Engineer  ...               12

[785741 rows x 18 columns]

In [120]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  str
 1   job_title              785740 non-null  str
 2   job_location           784696 non-null  str
 3   job_via                785733 non-null  str
 4   job_schedule_type      773074 non-null  str
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  str
 7   job_posted_date        785741 non-null  str
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  str
 11  salary_rate            33067 non-null   str
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  str
 15  job_skills             668704 non-null  str
 16  job_type_skills        668704 non-null  str
dtypes: bool(3), float64(2), str(12)
memory usage: 279.3 MB

In [125]:
df[df["salary_rate"].isnull()]

             job_title_short  ...                                    job_type_skills
0       Senior Data Engineer  ...                                                NaN
1               Data Analyst  ...  {'analyst_tools': ['power bi', 'tableau'], 'pr...
2              Data Engineer  ...  {'analyst_tools': ['dax'], 'cloud': ['azure'],...
3              Data Engineer  ...  {'cloud': ['aws'], 'libraries': ['tensorflow',...
4              Data Engineer  ...  {'cloud': ['oracle', 'aws'], 'other': ['ansibl...
...                      ...  ...                                                ...
785736     Software Engineer  ...  {'os': ['linux', 'unix'], 'other': ['kubernete...
785737          Data Analyst  ...  {'analyst_tools': ['sas', 'excel'], 'programmi...
785738      Business Analyst  ...         {'analyst_tools': ['powerpoint', 'excel']}
785739         Data Engineer  ...  {'cloud': ['aws', 'snowflake', 'azure', 'redsh...
785740     Software Engineer  ...              {'cloud': ['aws'], 'other': ['flow']}

[752674 rows x 17 columns]

In [129]:
df.dropna(subset="salary_rate", inplace=True)

In [130]:
df

             job_title_short  ...                                    job_type_skills
28            Data Scientist  ...  {'analyst_tools': ['excel'], 'libraries': ['gd...
43      Senior Data Engineer  ...  {'databases': ['sql server'], 'programming': [...
51      Senior Data Engineer  ...  {'cloud': ['aws', 'databricks'], 'libraries': ...
77             Data Engineer  ...  {'analyst_tools': ['tableau'], 'cloud': ['orac...
92             Data Engineer  ...                 {'programming': ['sql', 'python']}
...                      ...  ...                                                ...
785624         Data Engineer  ...  {'analyst_tools': ['alteryx', 'power bi', 'tab...
785641         Data Engineer  ...                                                NaN
785648        Data Scientist  ...  {'cloud': ['azure', 'snowflake'], 'libraries':...
785682        Data Scientist  ...  {'libraries': ['hadoop', 'spark', 'airflow'], ...
785692        Data Scientist  ...         {'programming': ['python', 'matlab', 'r']}

[33067 rows x 17 columns]

In [131]:
df.median()

TypeError: Cannot perform reduction 'median' with string dtype

In [132]:
df["salary_year_avg"].median()

np.float64(115000.0)

In [134]:
df["salary_hour_avg"].min()

np.float64(8.0)

In [135]:
# index of min

df["salary_hour_avg"].idxmin()

np.int64(88185)

In [139]:
df[88185]       # Find the column named 88185.

KeyError: 88185

In [136]:
df["salary_hour_avg"][88185]

np.float64(8.0)

In [144]:
df.iloc[88185:88186]

      job_title_short  ...                                    job_type_skills
88185  Data Scientist  ...  {'analyst_tools': ['word', 'tableau'], 'cloud'...

[1 rows x 17 columns]

In [145]:
min_salary = df["salary_year_avg"].min()


min_salary

np.float64(15000.0)

In [146]:
idx_min_salary = df["salary_year_avg"].idxmin()

idx_min_salary

665729

In [147]:
df.iloc[idx_min_salary: idx_min_salary + 1]

       job_title_short  ...                                    job_type_skills
665729   Data Engineer  ...  {'cloud': ['oracle', 'aws'], 'libraries': ['ha...

[1 rows x 17 columns]

In [148]:
df.iloc[idx_min_salary]

job_title_short                                              Data Engineer
job_title                                           Data Engineer - Hadoop
job_location                                                        Brazil
job_via                                                       via LinkedIn
job_schedule_type                                                Full-time
job_work_from_home                                                   False
search_location                                                     Brazil
job_posted_date                                        2023-12-09 10:05:30
job_no_degree_mention                                                 True
job_health_insurance                                                 False
job_country                                                         Brazil
salary_rate                                                           year
salary_year_avg                                                    15000.0
salary_hour_avg                                                        NaN
company_name                                               Net2Source Inc.
job_skills               ['java', 'python', 'oracle', 'aws', 'hadoop', ...
job_type_skills          {'cloud': ['oracle', 'aws'], 'libraries': ['ha...
Name: 665729, dtype: object

In [149]:
df["job_title_short"].unique()

<ArrowStringArray>
[     'Senior Data Engineer',              'Data Analyst',
             'Data Engineer',          'Business Analyst',
            'Data Scientist', 'Machine Learning Engineer',
       'Senior Data Analyst',            'Cloud Engineer',
     'Senior Data Scientist',         'Software Engineer']
Length: 10, dtype: str

In [150]:
df["job_title_short"].value_counts()

job_title_short
Data Analyst                 196075
Data Engineer                186241
Data Scientist               172286
Business Analyst              49063
Software Engineer             44929
Senior Data Engineer          44563
Senior Data Scientist         36957
Senior Data Analyst           29216
Machine Learning Engineer     14080
Cloud Engineer                12331
Name: count, dtype: int64