# sample() = randomly pick some data from your DataFrame.

* sample(n=3): If we want a specific number of random rows, then we should use n.
* sample(frac=0.4): frac means fraction. Instead of saying how many rows we want, we say what proportion of the DataFrame we want
 
 Example :
Our DataFrame has 5 rows.

df.sample(frac=0.4)

0.4 = 40%.

So:

40% of 5 rows = 2 rows

Therefore, it randomly selects approximately 2 rows.

* df.sample(n=2, random_state=42): Using random_state=42 ensures that you get the same sample, 42 isn't special. we could use - random_state=10, random_state=100
* df.sample(n=3, replace=True): Normally, sample() selects rows without replacement, when set to "True" it means "Duplicates are allowed"
* df.sample(n=2, axis=1): Sampling columns, By default, sample() selects rows. "This randomly selects 2 columns"




df.sample(

    n=2,

    frac=None,

    replace=False,

    random_state=42,

    axis=0

)

In [1]:
import pandas as pd

data = {
    "Name": ["Asha", "Ravi", "John", "Priya", "Rahul"],
    "Age": [20, 21, 19, 22, 20],
    "Marks": [85, 90, 78, 95, 88]
}

df = pd.DataFrame(data)

print(df)

    Name  Age  Marks
0   Asha   20     85
1   Ravi   21     90
2   John   19     78
3  Priya   22     95
4  Rahul   20     88

In [3]:
df.sample()

   Name  Age  Marks
2  John   19     78

In [4]:
df.sample(n=3)

    Name  Age  Marks
4  Rahul   20     88
1   Ravi   21     90
3  Priya   22     95

In [5]:
df.sample(frac=0.4)

    Name  Age  Marks
4  Rahul   20     88
3  Priya   22     95

In [6]:
df.sample(n=3, replace=True)

   Name  Age  Marks
0  Asha   20     85
2  John   19     78
2  John   19     78

In [7]:
df.sample(n=3, random_state=42)

    Name  Age  Marks
1   Ravi   21     90
4  Rahul   20     88
2   John   19     78

In [8]:
df.sample(n=3, random_state=42)

    Name  Age  Marks
1   Ravi   21     90
4  Rahul   20     88
2   John   19     78

In [9]:
df.sample(n=3, random_state=42)

    Name  Age  Marks
1   Ravi   21     90
4  Rahul   20     88
2   John   19     78

In [10]:
df.sample(n=3)

    Name  Age  Marks
0   Asha   20     85
3  Priya   22     95
2   John   19     78

In [11]:
df.sample(n=3)

    Name  Age  Marks
4  Rahul   20     88
1   Ravi   21     90
2   John   19     78

In [12]:
df.sample(n=3)

   Name  Age  Marks
1  Ravi   21     90
2  John   19     78
0  Asha   20     85

In [13]:
df.sample(n=2, axis=1)

   Age   Name
0   20   Asha
1   21   Ravi
2   19   John
3   22  Priya
4   20  Rahul

In [15]:
df.head(3)  # only first 3 rows not random rows

   Name  Age  Marks
0  Asha   20     85
1  Ravi   21     90
2  John   19     78

In [16]:
df.tail(3)  # only lat 3 rows not random rows

    Name  Age  Marks
2   John   19     78
3  Priya   22     95
4  Rahul   20     88

# copy()

In [53]:
import pandas as pd
from datasets import load_dataset

df = load_dataset("lukebarousse/data_jobs")["train"].to_pandas()


df["job_posted_date"] = pd.to_datetime(df["job_posted_date"])

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  str
 1   job_title              785740 non-null  str
 2   job_location           784696 non-null  str
 3   job_via                785733 non-null  str
 4   job_schedule_type      773074 non-null  str
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  str
 7   job_posted_date        785741 non-null  datetime64[us]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  str
 11  salary_rate            33067 non-null   str
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  str
 15  job_skills             668704 non-null  str
 16  job_type_skills        668704 non-null  str
dtypes: bool(3), datetime64[us](1), float64(2), str(11)
memory usage: 265.1 MB

In [39]:
df_assigned = df

In [40]:
df_assigned.loc[:5, "salary_year_avg"]

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
Name: salary_year_avg, dtype: float64

In [41]:
df_assigned.loc[:5, ["salary_year_avg"]]

   salary_year_avg
0              NaN
1              NaN
2              NaN
3              NaN
4              NaN
5              NaN

In [42]:
median_salary_year_avg = df["salary_year_avg"].median()

In [43]:
median_salary_year_avg

np.float64(115000.0)

In [44]:
df_assigned["salary_year_avg"] = df_assigned["salary_year_avg"].fillna(median_salary_year_avg)

In [45]:
df_assigned.loc[:5, ["salary_year_avg"]]

   salary_year_avg
0         115000.0
1         115000.0
2         115000.0
3         115000.0
4         115000.0
5         115000.0

In [46]:
df.loc[:5, ["salary_year_avg"]]

   salary_year_avg
0         115000.0
1         115000.0
2         115000.0
3         115000.0
4         115000.0
5         115000.0

In [48]:
id(df) == id(df_assigned)

True

In [54]:
# Using copy() method from pandas

df_copy = df.copy()

In [55]:
print(f"ID of df:                                                           {id(df)}")
print(f"ID of df_copy:                                                      {id(df_copy)}")
print(f"Are the two dataframe pointing towards the same object ?            {id(df) == id(df_copy)}")

ID of df:                                                           4697593232
ID of df_copy:                                                      5220202000
Are the two dataframe pointing towards the same object ?            False

In [57]:
median_salary_year_avg = df["salary_year_avg"].median()

df_copy["salary_year_avg"] = df_copy["salary_year_avg"].fillna(median_salary_year_avg)

df_copy.loc[:5, ["salary_year_avg"]]

   salary_year_avg
0         115000.0
1         115000.0
2         115000.0
3         115000.0
4         115000.0
5         115000.0

In [58]:
df.loc[:5, "salary_year_avg"]

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
Name: salary_year_avg, dtype: float64