In [3]:
import pandas as pd

df = pd.read_csv('/Users/Harshitha_mahadev/Downloads/housing.csv')

In [7]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [8]:
len(df)

20640

In [9]:
# Total population - sum

df['population'].sum()

np.float64(29421840.0)

In [10]:
print(df['population'].sum())

29421840.0

In [21]:
! pip list      # these are the list of different libraries which we can install

Package                   Version
------------------------- -----------
anyio                     4.14.1
appnope                   0.1.4
argon2-cffi               25.1.0
argon2-cffi-bindings      25.1.0
arrow                     1.4.0
asttokens                 3.0.1
async-lru                 2.3.0
attrs                     26.1.0
babel                     2.18.0
beautifulsoup4            4.15.0
bleach                    6.4.0
certifi                   2026.6.17
cffi                      2.0.0
charset-normalizer        3.4.7
comm                      0.2.3
contourpy                 1.3.3
cycler                    0.12.1
debugpy                   1.8.21
decorator                 5.3.1
defusedxml                0.7.1
et_xmlfile                2.0.0
executing                 2.2.1
fastjsonschema            2.21.2
fonttools                 4.63.0
fqdn                      1.5.1
h11                       0.16.0
httpcore                  1.0.9
httpx                     0.28.1
idna                      3.18
ipykernel                 7.3.0
ipython                   9.14.1
ipython_pygments_lexers   1.1.1
ipywidgets                8.1.8
isoduration               20.11.0
jedi                      0.20.0
Jinja2                    3.1.6
json5                     0.15.0
jsonpointer               3.1.1
jsonschema                4.26.0
jsonschema-specifications 2025.9.1
jupyter                   1.1.1
jupyter_builder           1.0.2
jupyter_client            8.9.1
jupyter-console           6.6.3
jupyter_core              5.9.1
jupyter-events            0.12.1
jupyter-lsp               2.3.1
jupyter_server            2.20.0
jupyter_server_terminals  0.5.4
jupyterlab                4.6.0
jupyterlab_pygments       0.3.0
jupyterlab_server         2.28.0
jupyterlab_widgets        3.0.16
kiwisolver                1.5.0
lark                      1.3.1
MarkupSafe                3.0.3
matplotlib                3.11.0
matplotlib-inline         0.2.2
mistune                   3.3.2
nbclient                  0.11.0
nbconvert                 7.17.1
nbformat                  5.10.4
nest-asyncio2             1.7.2
notebook                  7.6.0
notebook_shim             0.2.4
numpy                     2.4.4
openpyxl                  3.1.5
packaging                 26.2
pandas                    3.0.2
pandocfilters             1.5.1
parso                     0.8.7
pexpect                   4.9.0
pillow                    12.2.0
pip                       26.1.2
platformdirs              4.10.0
prometheus_client         0.25.0
prompt_toolkit            3.0.52
psutil                    7.2.2
ptyprocess                0.7.0
pure_eval                 0.2.3
pycparser                 3.0
Pygments                  2.20.0
pyparsing                 3.3.2
python-dateutil           2.9.0.post0
python-json-logger        4.1.0
PyYAML                    6.0.3
pyzmq                     27.1.0
referencing               0.37.0
requests                  2.34.2
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rfc3987-syntax            1.1.0
rpds-py                   2026.5.1
seaborn                   0.13.2
Send2Trash                2.1.0
six                       1.17.0
soupsieve                 2.8.4
stack-data                0.6.3
terminado                 0.18.1
tinycss2                  1.5.1
tornado                   6.5.7
traitlets                 5.15.1
typing_extensions         4.15.0
tzdata                    2026.2
uri-template              1.3.0
urllib3                   2.7.0
wcwidth                   0.8.1
webcolors                 25.10.0
webencodings              0.5.1
websocket-client          1.9.0
widgetsnbextension        4.0.15

In [27]:
# !pip install pyjokes            # shell(os-Terminal or Command Prompt)

# !python -m install pyjokes    # Find the specified module > Run that module as a program

%pip install pyjokes          # jupyter

Requirement already satisfied: pyjokes in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (0.8.3)

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [31]:
import pyjokes

In [32]:
help(pyjokes)

Help on package pyjokes:

NAME
    pyjokes

PACKAGE CONTENTS
    cli (package)
    exc
    jokes_cs
    jokes_de
    jokes_en
    jokes_es
    jokes_eu
    jokes_fr
    jokes_gl
    jokes_hu
    jokes_it
    jokes_lt
    jokes_pl
    jokes_ru
    jokes_sv
    pyjokes

DATA
    CATEGORY_VALUES = {'all', 'chuck', 'neutral'}
    LANGUAGE_VALUES = {'cs', 'de', 'en', 'es', 'eu', 'fr', ...}

FILE
    /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/pyjokes/__init__.py

In [33]:
pyjokes.get_joke()

'The best thing about a Boolean is that even if you are wrong, you are only off by a bit.'

In [34]:
pyjokes.get_jokes()

["Complaining about the lack of smoking shelters, the nicotine addicted Python programmers said there ought to be 'spaces for tabs'.",
 'Ubuntu users are apt to get this joke.',
 'Obfuscated Reality Mappers (ORMs) can be useful database tools.',
 'Asked to explain Unicode during an interview, Geoff went into detail about his final year university project. He was not hired.',
 "Triumphantly, Beth removed Python 2.7 from her server in 2030. 'Finally!' she said with glee, only to see the announcement for Python 4.4.",
 "An SQL query goes into a bar, walks up to two tables and asks, 'Can I join you?'",
 'When your hammer is C++, everything begins to look like a thumb.',
 'If you put a million monkeys at a million keyboards, one of them will eventually write a Java program. The rest of them will write Perl.',
 'To understand recursion you must first understand recursion.',
 "I suggested holding a 'Python Object Oriented Programming Seminar', but the acronym was unpopular.",
 "'Knock, knock.' 'Who's there?' ... very long pause ... 'Java.'",
 "How many programmers does it take to change a lightbulb? None, that's a hardware problem.",
 "What's the object-oriented way to become wealthy? Inheritance.",
 "Why don't jokes work in octal? Because 7 10 11.",
 'How many programmers does it take to change a lightbulb? None, they just make darkness a standard.',
 "Two bytes meet. The first byte asks, 'Are you ill?' The second byte replies, 'No, just feeling a bit off.'",
 "Two threads walk into a bar. The barkeeper looks up and yells, 'Hey, I want don't any conditions race like time last!'",
 "Old C programmers don't die, they're just cast into void.",
 "Eight bytes walk into a bar. The bartender asks, 'Can I get you anything?' 'Yeah,' replies the bytes. 'Make us a double.'",
 "Why did the programmer quit his job? Because he didn't get arrays.",
 "Why do Java programmers have to wear glasses? Because they don't see sharp.",
 'Software developers like to solve problems. If there are no problems handily available, they will create their own.',
 ".NET was named .NET so that it wouldn't show up in a Unix directory listing.",
 'Hardware: The part of a computer that you can kick.',
 "A programmer was found dead in the shower. Next to their body was a bottle of shampoo with the instructions 'Lather, Rinse and Repeat'.",
 'Optimist: The glass is half full. Pessimist: The glass is half empty. Programmer: The glass is twice as large as necessary.',
 'In C we had to code our own bugs. In C++ we can inherit them.',
 'How come there is no obfuscated Perl contest? Because everyone would win.',
 "If you play a Windows CD backwards, you'll hear satanic chanting ... worse still, if you play it forwards, it installs Windows.",
 'How many programmers does it take to kill a cockroach? Two: one holds, the other installs Windows on it.',
 'What do you call a programmer from Finland? Nerdic.',
 "What did the Java code say to the C code? A: You've got no class.",
 "Why did Microsoft name their search engine BING? Because It's Not Google.",
 "Pirates go 'arg!', computer pirates go 'argv!'",
 'Software salesmen and used-car salesmen differ in that the latter know when they are lying.',
 "Child: Dad, why does the sun rise in the east and set in the west? Dad: Son, it's working, don't touch it.",
 'Why do programmers confuse Halloween with Christmas? Because OCT 31 == DEC 25.',
 'How many Prolog programmers does it take to change a lightbulb? false.',
 'Real programmers can write assembly code in any language.',
 'Waiter: Would you like coffee or tea? Programmer: Yes.',
 'What do you get when you cross a cat and a dog? Cat dog sin theta.',
 "If loving you is ROM I don't wanna read write.",
 'A programmer walks into a foo...',
 "A programmer walks into a bar and orders 1.38 root beers. The bartender informs her it's a root beer float. She says 'Make it a double!'",
 "What is Benoit B. Mandelbrot's middle name? Benoit B. Mandelbrot.",
 "Why are you always smiling? That's just my... regular expression.",
 'ASCII stupid question, get a stupid ANSI.',
 "A programmer had a problem. He thought to himself, 'I know, I'll solve it with threads!'. has Now problems. two he",
 'Why do sin and tan work? Just cos.',
 'Java: Write once, run away.',
 'I would tell you a joke about UDP, but you would never get it.',
 'A QA engineer walks into a bar. Runs into a bar. Crawls into a bar. Dances into a bar. Tiptoes into a bar. Rams a bar. Jumps into a bar.',
 "My friend's in a band called '1023 Megabytes'... They haven't got a gig yet!",
 "I had a problem so I thought I'd use Java. Now I have a ProblemFactory.",
 'QA Engineer walks into a bar. Orders a beer. Orders 0 beers. Orders 999999999 beers. Orders a lizard. Orders -1 beers. Orders a sfdeljknesv.',
 'A product manager walks into a bar, asks for drink. Bartender says no, but will consider adding later.',
 'How do you generate a random string? Put a first year Computer Science student in Vim and ask them to save and exit.',
 "I've been using Vim for a long time now, mainly because I can't figure out how to exit.",
 "How do you know whether a person is a Vim user? Don't worry, they'll tell you.",
 "Waiter: He's choking! Is anyone a doctor? Programmer: I'm a Vim user.",
 "3 Database Admins walked into a NoSQL bar. A little while later they walked out because they couldn't find a table.",
 'How to explain the movie Inception to a programmer? When you run a VM inside another VM, inside another VM ... everything runs real slow!',
 'What do you call a parrot that says "Squawk! Pieces of nine! Pieces of nine!"? A parrot-ey error.',
 'There are only two hard problems in Computer Science: cache invalidation, naming things and off-by-one-errors.',
 "There are 10 types of people: those who understand binary and those who don't.",
 'There are 2 types of people: those who can extrapolate from incomplete data sets...',
 "There are II types of people: Those who understand Roman Numerals and those who don't.",
 'There are 10 types of people: those who understand hexadecimal and 15 others.',
 "There are 10 types of people: those who understand binary, those who don't, and those who were expecting this joke to be in trinary.",
 "There are 10 types of people: those who understand trinary, those who don't, and those who have never heard of it.",
 'What do you call eight hobbits? A hobbyte.',
 'The best thing about a Boolean is even if you are wrong, you are only off by a bit.',
 'A good programmer is someone who always looks both ways before crossing a one-way street.',
 'There are two ways to write error-free programs; only the third one works.',
 'QAs consist of 55% water, 30% blood and 15% Jira tickets.',
 'Sympathy for the Devil is really just about being nice to QAs.',
 "How many QAs does it take to change a lightbulb? They noticed that the room was dark. They don't fix problems, they find them.",
 'A programmer crashes a car at the bottom of a hill, a bystander asks what happened, he says "No idea. Let\'s push it back up and try again".',
 "What do you mean 911 is only for emergencies? I've got a merge conflict.",
 "Writing PHP is like peeing in the swimming pool, everyone did it, but we don't need to bring it up in public.",
 "Why did the QA cross the road? To ruin everyone's day.",
 'Number of days since I have encountered an array index error: -1.',
 'Number of days since I have encountered an off-by-one error: 0.',
 'Speed dating is useless. 5 minutes is not enough to properly explain the benefits of the Unix philosophy.',
 'Microsoft hold a bi-monthly internal "productive week" where they use Google instead of Bing.',
 "Schrodinger's attitude to web development: If I don't look at it in Internet Explorer then there's a chance it looks fine.",
 'Finding a good PHP developer is like looking for a needle in a haystack. Or is it a hackstack in a needle?',
 "Unix is user friendly. It's just very particular about who its friends are.",
 'A COBOL programmer makes millions with Y2K remediation and decides to get cryogenically frozen. "The year is 9999. You know COBOL, right?"',
 'The C language combines all the power of assembly language with all the ease-of-use of assembly language.',
 'An SEO expert walks into a bar, bars, pub, public house, Irish pub, tavern, bartender, beer, liquor, wine, alcohol, spirits...',
 "What does 'Emacs' stand for? 'Exclusively used by middle aged computer scientists.'",
 'What does pyjokes have in common with Adobe Flash? It gets updated all the time, but never gets any better.',
 "Why does Waldo only wear stripes? Because he doesn't want to be spotted.",
 'I went to a street where the houses were numbered 8k, 16k, 32k, 64k, 128k, 256k and 512k. It was a trip down Memory Lane.',
 "!false, (It's funny because it's true)",
 "['hip', 'hip'] (hip hip array!)",
 "Programmer: The ship I boarded crashed and I am dying! Project Manager: Then let's do a quick knowledge transfer session before you go.",
 'Are you a RESTful API? because you GET my attention, PUT some love, POST the cutest smile, and DELETE my bad day.',
 'I used to know a joke about Java, but I run out of memory.',
 'My girlfriend dumped me after I named a class after her. She felt I treated her like an object.',
 'Girl: Do you drink? Programmer: No. Girl: Have Girlfriend? Programmer: No. Girl: Then how do you enjoy life? Programmer: I am Programmer',
 'A Programmer was walking out of door for work, his wife said "while you\'re out, buy some milk" and he never returned.',
 'A: What is your address? Me: 173.168.15.10 A: No, your local address Me: 127.0.0.1 A: I mean your physical address B: 29:01:38:62:31:58',
 'Why do programmers always mix up Halloween and Christmas? Because Oct 31 equals Dec 25.',
 'Programming is 10% science, 20% ingenuity, and 70% getting the ingenuity to work with the science.',
 'There are three kinds of lies: Lies, damned lies, and benchmarks.',
 'All programmers are playwrights, and all computers are lousy actors.',
 "Have you heard about the new Cray super computer? It's so fast, it executes an infinite loop in 6 seconds.",
 'The generation of random numbers is too important to be left to chance.',
 'I just saw my life flash before my eyes and all I could see was a close tag.',
 'The computer is mightier than the pen, the sword, and usually, the programmer',
 'Debugging: Removing the needles from the haystack.',
 'If doctors were like software engineers, they would say things like Have you tried killing yourself and being reborn?',
 'Debugging is like being the detective in a crime drama where you are also the murderer.',
 'The best thing about a Boolean is that even if you are wrong, you are only off by a bit.',
 'If you listen to a UNIX shell, can you hear the C?',
 "Why do Java programmers have to wear glasses? Because they don't C#.",
 'When Apple employees die, does their life HTML5 in front of their eyes?',
 'What did the router say to the doctor? It hurts when IP.',
 'Learning JavaScript is like looking both ways before you cross the street, and then getting hit by an airplane.',
 'I for one am excited for the days when dereferencing a null pointer causes an aneurysm.',
 'Debugging is like an onion. There are multiple layers to it, and the more you peel them back.',
 "When your code does not change color automatically, Something's wrong, I can feel it.",
 'I have a joke on programming but it only works on my computer.',
 "Why do you always use i and j variales in loops? It's the law......",
 'As far as we know, our computer has never had an undetected error.',
 'A user friendly computer first requires a friendly user.',
 "Bug? That's not a bug, that's a feature.",
 'Buy a Pentium 586/200 so you can reboot faster.',
 "Computer analyst to programmer: You start coding. I'll go find out what they want.",
 'Computer programmers do it byte by byte.',
 "Don't compute and drive; the life you save may be your own.",
 'How an engineer writes a program: Start by debugging an empty file...',
 "If at first you don't succeed, call it version 1.0.",
 'I have a dream: 1073741824 bytes free.',
 "I haven't lost my mind; it's backed up on tape somewhere.",
 'Is reading in the bathroom considered Multi-Tasking.',
 "Never say 'OOPS!' always say 'Ah, Interesting!'",
 "One person's error is another person's data.",
 'Press CTRL-ALT-DEL to continue....',
 "Programmer's Time-Space Continuum: Programmers continuously space the time.",
 'Speed Kills! Use Windows.',
 "The box said: 'install on Windows 95, NT 4.0 or better'. So I installed it on Linux.",
 'The program is absolutely right; therefore the computer must be wrong.',
 "There are only 10 types of people in this world: those who understand binary, and those who don't.",
 'There were computers in Biblical times. Eve had an Apple.',
 'Those who can, do. Those who cannot, teach. Those who cannot teach, HACK!',
 'User error: replace user and press any key to continue.',
 'Warning, keyboard not found. Press Enter to continue.',
 "Why do they call this a word processor? It's simple, ... you've seen what food processors do to food, right?",
 'Why do we want intelligent terminals when there are so many stupid users?',
 'Windows is NOT a virus. Viruses DO something.',
 'WINDOWS stands for Will Install Needless Data On Whole System.',
 'You are making progress if each mistake is a new one.',
 'You had mail, but the super-user read it, and deleted it!',
 'You never finish a program, you just stop working on it.',
 "You don't have to know how the computer works, just how to work the computer.",
 "You forgot to do your backup 16 days ago. Tomorrow you'll need that version.",
 "I love pressing the F5 key. It's refreshing.",
 'My favourite computer based band is the Black IPs.',
 "Why was the developer bankrupt? He'd used all his cache.",
 "A friend is in a band called 1023Mb. They haven't had a gig yet.",
 "Apparently my password needs to be capitals only so I've changed it to LONDONMADRIDROME",
 "I changed my password to BeefStew but the computer told me it wasn't Stroganoff.",
 "Changed my password to fortnight but apparently that's two week.",
 'Artificial intelligence usually beats real stupidity.',
 'The Internet: where men are men, women are men, and children are FBI agents.',
 'Bugs come in through open Windows.',
 "Unix is user friendly. It's just selective about who its friends are.",
 'Failure is not an option. It comes bundled with your Microsoft product.',
 'Computers are like air conditioners: they stop working when you open Windows.',
 'Beware of programmers that carry screwdrivers.',
 "I'm not anti-social; I'm just not user friendly.",
 'Hey! It compiles! Ship it!',
 "If Ruby is not and Perl is the answer, you don't understand the question.",
 "My attitude isn't bad. It's in beta.",
 'Programmers are tools for converting caffeine into code.',
 "There are three kinds of people: those who can count and those who can't.",
 'Why do programmers prefer dark mode? Because light attracts bugs.']

In [36]:
len(pyjokes.get_jokes())

180

In [38]:
count = 0

for jokes in pyjokes.get_jokes():
    count += 1


print(count)

180

In [39]:
for jokes in pyjokes.get_jokes():
    print(jokes)

Complaining about the lack of smoking shelters, the nicotine addicted Python programmers said there ought to be 'spaces for tabs'.
Ubuntu users are apt to get this joke.
Obfuscated Reality Mappers (ORMs) can be useful database tools.
Asked to explain Unicode during an interview, Geoff went into detail about his final year university project. He was not hired.
Triumphantly, Beth removed Python 2.7 from her server in 2030. 'Finally!' she said with glee, only to see the announcement for Python 4.4.
An SQL query goes into a bar, walks up to two tables and asks, 'Can I join you?'
When your hammer is C++, everything begins to look like a thumb.
If you put a million monkeys at a million keyboards, one of them will eventually write a Java program. The rest of them will write Perl.
To understand recursion you must first understand recursion.
I suggested holding a 'Python Object Oriented Programming Seminar', but the acronym was unpopular.
'Knock, knock.' 'Who's there?' ... very long pause ... 'Java.'
How many programmers does it take to change a lightbulb? None, that's a hardware problem.
What's the object-oriented way to become wealthy? Inheritance.
Why don't jokes work in octal? Because 7 10 11.
How many programmers does it take to change a lightbulb? None, they just make darkness a standard.
Two bytes meet. The first byte asks, 'Are you ill?' The second byte replies, 'No, just feeling a bit off.'
Two threads walk into a bar. The barkeeper looks up and yells, 'Hey, I want don't any conditions race like time last!'
Old C programmers don't die, they're just cast into void.
Eight bytes walk into a bar. The bartender asks, 'Can I get you anything?' 'Yeah,' replies the bytes. 'Make us a double.'
Why did the programmer quit his job? Because he didn't get arrays.
Why do Java programmers have to wear glasses? Because they don't see sharp.
Software developers like to solve problems. If there are no problems handily available, they will create their own.
.NET was named .NET so that it wouldn't show up in a Unix directory listing.
Hardware: The part of a computer that you can kick.
A programmer was found dead in the shower. Next to their body was a bottle of shampoo with the instructions 'Lather, Rinse and Repeat'.
Optimist: The glass is half full. Pessimist: The glass is half empty. Programmer: The glass is twice as large as necessary.
In C we had to code our own bugs. In C++ we can inherit them.
How come there is no obfuscated Perl contest? Because everyone would win.
If you play a Windows CD backwards, you'll hear satanic chanting ... worse still, if you play it forwards, it installs Windows.
How many programmers does it take to kill a cockroach? Two: one holds, the other installs Windows on it.
What do you call a programmer from Finland? Nerdic.
What did the Java code say to the C code? A: You've got no class.
Why did Microsoft name their search engine BING? Because It's Not Google.
Pirates go 'arg!', computer pirates go 'argv!'
Software salesmen and used-car salesmen differ in that the latter know when they are lying.
Child: Dad, why does the sun rise in the east and set in the west? Dad: Son, it's working, don't touch it.
Why do programmers confuse Halloween with Christmas? Because OCT 31 == DEC 25.
How many Prolog programmers does it take to change a lightbulb? false.
Real programmers can write assembly code in any language.
Waiter: Would you like coffee or tea? Programmer: Yes.
What do you get when you cross a cat and a dog? Cat dog sin theta.
If loving you is ROM I don't wanna read write.
A programmer walks into a foo...
A programmer walks into a bar and orders 1.38 root beers. The bartender informs her it's a root beer float. She says 'Make it a double!'
What is Benoit B. Mandelbrot's middle name? Benoit B. Mandelbrot.
Why are you always smiling? That's just my... regular expression.
ASCII stupid question, get a stupid ANSI.
A programmer had a problem. He thought to himself, 'I know, I'll solve it with threads!'. has Now problems. two he
Why do sin and tan work? Just cos.
Java: Write once, run away.
I would tell you a joke about UDP, but you would never get it.
A QA engineer walks into a bar. Runs into a bar. Crawls into a bar. Dances into a bar. Tiptoes into a bar. Rams a bar. Jumps into a bar.
My friend's in a band called '1023 Megabytes'... They haven't got a gig yet!
I had a problem so I thought I'd use Java. Now I have a ProblemFactory.
QA Engineer walks into a bar. Orders a beer. Orders 0 beers. Orders 999999999 beers. Orders a lizard. Orders -1 beers. Orders a sfdeljknesv.
A product manager walks into a bar, asks for drink. Bartender says no, but will consider adding later.
How do you generate a random string? Put a first year Computer Science student in Vim and ask them to save and exit.
I've been using Vim for a long time now, mainly because I can't figure out how to exit.
How do you know whether a person is a Vim user? Don't worry, they'll tell you.
Waiter: He's choking! Is anyone a doctor? Programmer: I'm a Vim user.
3 Database Admins walked into a NoSQL bar. A little while later they walked out because they couldn't find a table.
How to explain the movie Inception to a programmer? When you run a VM inside another VM, inside another VM ... everything runs real slow!
What do you call a parrot that says "Squawk! Pieces of nine! Pieces of nine!"? A parrot-ey error.
There are only two hard problems in Computer Science: cache invalidation, naming things and off-by-one-errors.
There are 10 types of people: those who understand binary and those who don't.
There are 2 types of people: those who can extrapolate from incomplete data sets...
There are II types of people: Those who understand Roman Numerals and those who don't.
There are 10 types of people: those who understand hexadecimal and 15 others.
There are 10 types of people: those who understand binary, those who don't, and those who were expecting this joke to be in trinary.
There are 10 types of people: those who understand trinary, those who don't, and those who have never heard of it.
What do you call eight hobbits? A hobbyte.
The best thing about a Boolean is even if you are wrong, you are only off by a bit.
A good programmer is someone who always looks both ways before crossing a one-way street.
There are two ways to write error-free programs; only the third one works.
QAs consist of 55% water, 30% blood and 15% Jira tickets.
Sympathy for the Devil is really just about being nice to QAs.
How many QAs does it take to change a lightbulb? They noticed that the room was dark. They don't fix problems, they find them.
A programmer crashes a car at the bottom of a hill, a bystander asks what happened, he says "No idea. Let's push it back up and try again".
What do you mean 911 is only for emergencies? I've got a merge conflict.
Writing PHP is like peeing in the swimming pool, everyone did it, but we don't need to bring it up in public.
Why did the QA cross the road? To ruin everyone's day.
Number of days since I have encountered an array index error: -1.
Number of days since I have encountered an off-by-one error: 0.
Speed dating is useless. 5 minutes is not enough to properly explain the benefits of the Unix philosophy.
Microsoft hold a bi-monthly internal "productive week" where they use Google instead of Bing.
Schrodinger's attitude to web development: If I don't look at it in Internet Explorer then there's a chance it looks fine.
Finding a good PHP developer is like looking for a needle in a haystack. Or is it a hackstack in a needle?
Unix is user friendly. It's just very particular about who its friends are.
A COBOL programmer makes millions with Y2K remediation and decides to get cryogenically frozen. "The year is 9999. You know COBOL, right?"
The C language combines all the power of assembly language with all the ease-of-use of assembly language.
An SEO expert walks into a bar, bars, pub, public house, Irish pub, tavern, bartender, beer, liquor, wine, alcohol, spirits...
What does 'Emacs' stand for? 'Exclusively used by middle aged computer scientists.'
What does pyjokes have in common with Adobe Flash? It gets updated all the time, but never gets any better.
Why does Waldo only wear stripes? Because he doesn't want to be spotted.
I went to a street where the houses were numbered 8k, 16k, 32k, 64k, 128k, 256k and 512k. It was a trip down Memory Lane.
!false, (It's funny because it's true)
['hip', 'hip'] (hip hip array!)
Programmer: The ship I boarded crashed and I am dying! Project Manager: Then let's do a quick knowledge transfer session before you go.
Are you a RESTful API? because you GET my attention, PUT some love, POST the cutest smile, and DELETE my bad day.
I used to know a joke about Java, but I run out of memory.
My girlfriend dumped me after I named a class after her. She felt I treated her like an object.
Girl: Do you drink? Programmer: No. Girl: Have Girlfriend? Programmer: No. Girl: Then how do you enjoy life? Programmer: I am Programmer
A Programmer was walking out of door for work, his wife said "while you're out, buy some milk" and he never returned.
A: What is your address? Me: 173.168.15.10 A: No, your local address Me: 127.0.0.1 A: I mean your physical address B: 29:01:38:62:31:58
Why do programmers always mix up Halloween and Christmas? Because Oct 31 equals Dec 25.
Programming is 10% science, 20% ingenuity, and 70% getting the ingenuity to work with the science.
There are three kinds of lies: Lies, damned lies, and benchmarks.
All programmers are playwrights, and all computers are lousy actors.
Have you heard about the new Cray super computer? It's so fast, it executes an infinite loop in 6 seconds.
The generation of random numbers is too important to be left to chance.
I just saw my life flash before my eyes and all I could see was a close tag.
The computer is mightier than the pen, the sword, and usually, the programmer
Debugging: Removing the needles from the haystack.
If doctors were like software engineers, they would say things like Have you tried killing yourself and being reborn?
Debugging is like being the detective in a crime drama where you are also the murderer.
The best thing about a Boolean is that even if you are wrong, you are only off by a bit.
If you listen to a UNIX shell, can you hear the C?
Why do Java programmers have to wear glasses? Because they don't C#.
When Apple employees die, does their life HTML5 in front of their eyes?
What did the router say to the doctor? It hurts when IP.
Learning JavaScript is like looking both ways before you cross the street, and then getting hit by an airplane.
I for one am excited for the days when dereferencing a null pointer causes an aneurysm.
Debugging is like an onion. There are multiple layers to it, and the more you peel them back.
When your code does not change color automatically, Something's wrong, I can feel it.
I have a joke on programming but it only works on my computer.
Why do you always use i and j variales in loops? It's the law......
As far as we know, our computer has never had an undetected error.
A user friendly computer first requires a friendly user.
Bug? That's not a bug, that's a feature.
Buy a Pentium 586/200 so you can reboot faster.
Computer analyst to programmer: You start coding. I'll go find out what they want.
Computer programmers do it byte by byte.
Don't compute and drive; the life you save may be your own.
How an engineer writes a program: Start by debugging an empty file...
If at first you don't succeed, call it version 1.0.
I have a dream: 1073741824 bytes free.
I haven't lost my mind; it's backed up on tape somewhere.
Is reading in the bathroom considered Multi-Tasking.
Never say 'OOPS!' always say 'Ah, Interesting!'
One person's error is another person's data.
Press CTRL-ALT-DEL to continue....
Programmer's Time-Space Continuum: Programmers continuously space the time.
Speed Kills! Use Windows.
The box said: 'install on Windows 95, NT 4.0 or better'. So I installed it on Linux.
The program is absolutely right; therefore the computer must be wrong.
There are only 10 types of people in this world: those who understand binary, and those who don't.
There were computers in Biblical times. Eve had an Apple.
Those who can, do. Those who cannot, teach. Those who cannot teach, HACK!
User error: replace user and press any key to continue.
Warning, keyboard not found. Press Enter to continue.
Why do they call this a word processor? It's simple, ... you've seen what food processors do to food, right?
Why do we want intelligent terminals when there are so many stupid users?
Windows is NOT a virus. Viruses DO something.
WINDOWS stands for Will Install Needless Data On Whole System.
You are making progress if each mistake is a new one.
You had mail, but the super-user read it, and deleted it!
You never finish a program, you just stop working on it.
You don't have to know how the computer works, just how to work the computer.
You forgot to do your backup 16 days ago. Tomorrow you'll need that version.
I love pressing the F5 key. It's refreshing.
My favourite computer based band is the Black IPs.
Why was the developer bankrupt? He'd used all his cache.
A friend is in a band called 1023Mb. They haven't had a gig yet.
Apparently my password needs to be capitals only so I've changed it to LONDONMADRIDROME
I changed my password to BeefStew but the computer told me it wasn't Stroganoff.
Changed my password to fortnight but apparently that's two week.
Artificial intelligence usually beats real stupidity.
The Internet: where men are men, women are men, and children are FBI agents.
Bugs come in through open Windows.
Unix is user friendly. It's just selective about who its friends are.
Failure is not an option. It comes bundled with your Microsoft product.
Computers are like air conditioners: they stop working when you open Windows.
Beware of programmers that carry screwdrivers.
I'm not anti-social; I'm just not user friendly.
Hey! It compiles! Ship it!
If Ruby is not and Perl is the answer, you don't understand the question.
My attitude isn't bad. It's in beta.
Programmers are tools for converting caffeine into code.
There are three kinds of people: those who can count and those who can't.
Why do programmers prefer dark mode? Because light attracts bugs.

In [40]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [41]:
df.tail()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [42]:
df.shape

(20640, 10)

In [45]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20433.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,537.870553,1425.476744,499.539680,3.870671,206855.816909
std,2.003532,2.135952,12.585558,2181.615252,421.385070,1132.462122,382.329753,1.899822,115395.615874
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,787.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1725.000000,605.000000,4.743250,264725.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [47]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='str')

In [48]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  str
dtypes: float64(9), str(1)
memory usage: 1.6 MB

In [49]:
df.isnull()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
20635,False,False,False,False,False,False,False,False,False,False
20636,False,False,False,False,False,False,False,False,False,False
20637,False,False,False,False,False,False,False,False,False,False
20638,False,False,False,False,False,False,False,False,False,False
20639,False,False,False,False,False,False,False,False,False,False

In [52]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [60]:
df['total_bedrooms'].isnull().sum()

np.int64(207)

In [8]:
[null for null in df['total_bedrooms'] if df['total_bedrooms'].isnull()]        # Because df['total_bedrooms'].isnull() - this consists a sequence of Boolean values

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [ ]:
""" 
    Suppose if this comes as the result:
    longitude	latitude	total_bedrooms	population          # This gives us the DataFrame
    -122.24	    37.85   	NaN	            496
    
    So, that the reason why when we loop the DataFrame, 'Python only gives us the coulmn names of the DataFrame'
"""

[null for null in df[df["total_bedrooms"].isnull()]]

['longitude',
 'latitude',
 'housing_median_age',
 'total_rooms',
 'total_bedrooms',
 'population',
 'households',
 'median_income',
 'median_house_value',
 'ocean_proximity']

In [10]:
[null for null in df]

['longitude',
 'latitude',
 'housing_median_age',
 'total_rooms',
 'total_bedrooms',
 'population',
 'households',
 'median_income',
 'median_house_value',
 'ocean_proximity']

In [63]:
df['total_bedrooms']        # Pandas gives us Series, those objects below are called as Series

0         129.0
1        1106.0
2         190.0
3         235.0
4         280.0
          ...
20635     374.0
20636     150.0
20637     485.0
20638     409.0
20639     616.0
Name: total_bedrooms, Length: 20640, dtype: float64

In [64]:
df['total_bedrooms'].isnull()   # returns new Series - True / False

0        False
1        False
2        False
3        False
4        False
         ...
20635    False
20636    False
20637    False
20638    False
20639    False
Name: total_bedrooms, Length: 20640, dtype: bool

In [79]:
df[df['total_bedrooms'].isnull()]           # df[True]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
290,-122.16,37.77,47.0,1256.0,NaN,570.0,218.0,4.3750,161900.0,NEAR BAY
341,-122.17,37.75,38.0,992.0,NaN,732.0,259.0,1.6196,85100.0,NEAR BAY
538,-122.28,37.78,29.0,5154.0,NaN,3741.0,1273.0,2.5762,173400.0,NEAR BAY
563,-122.24,37.75,45.0,891.0,NaN,384.0,146.0,4.9489,247100.0,NEAR BAY
696,-122.10,37.69,41.0,746.0,NaN,387.0,161.0,3.9063,178400.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20267,-119.19,34.20,18.0,3620.0,NaN,3171.0,779.0,3.3409,220500.0,NEAR OCEAN
20268,-119.18,34.19,19.0,2393.0,NaN,1938.0,762.0,1.6953,167400.0,NEAR OCEAN
20372,-118.88,34.17,15.0,4260.0,NaN,1701.0,669.0,5.1033,410700.0,<1H OCEAN
20460,-118.75,34.29,17.0,5512.0,NaN,2734.0,814.0,6.6073,258100.0,<1H OCEAN
20484,-118.72,34.28,17.0,3051.0,NaN,1705.0,495.0,5.7376,218600.0,<1H OCEAN

# not vs ~ 

## Suppose we have one light bulb.

### Not

#### works
* On -> Off 

* Off -> On


#### doesn't work (Error!) - "not" does not work all together only supported for single value
* On    ->      Off
* Off   ->      On
* On    ->      Off 
* On    ->      Off
* Off   ->      On
* On    ->      Off
  

### ~
#### works all together
* On    ->      Off
* Off   ->      On
* On    ->      Off 
* On    ->      Off
* Off   ->      On
* On    ->      Off

In [75]:
# To extract the True - "is null"

df[not df['total_bedrooms'].isnull()]     # Beacuse it consists of many Boolean values

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [4]:
# To extract the False - "is null"

df[~ df['total_bedrooms'].isnull()]   

# or 

df[df["total_bedrooms"].notnull()]

# or

df[df["total_bedrooms"].notna()]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [5]:
df[df["total_bedrooms"].notnull()]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND